language: python
python: '3.7'
dist: xenial
sudo: true
addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-latex-recommended
    - texlive-generic-recommended
    - texlive-pictures
    - texlive-publishers
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - cmake
    - xsltproc
before_cache:
- sudo chown -R travis:travis $HOME
- sudo chown -R travis:travis $TRAVIS_BUILD_DIR
cache:
  directories:
  - "~/.modules"
  - "~/.local"
  timeout: 1000
  apt: true
git:
  depth: 1
services:
- mysql
- mongodb
- xvfb
before_install:
- openssl aes-256-cbc -K $encrypted_a7e0fbcaffa3_key -iv $encrypted_a7e0fbcaffa3_iv
  -in ./mmeds/secrets.py.enc -out mmeds/secrets.py -d
- openssl aes-256-cbc -K $encrypted_754fbe69cba7_key -iv $encrypted_754fbe69cba7_iv
  -in ./mmeds/resources/privkey.pem.enc -out ./mmeds/resources/privkey.pem -d
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O ~/miniconda.sh
  --quiet
- chmod +x ~/miniconda.sh
- "~/miniconda.sh -b &>/dev/null"
- export PATH=~/miniconda2/bin:$PATH
- conda update --yes conda &>/dev/null
- sudo chown -R travis:travis ~/.modules/modulefiles
- sudo chown -R travis:travis ~/.modules ~/.local
- bash travis_setup.sh
- source ~/.bashrc
- conda info --envs
install:
- source activate mmeds-stable
- pip install . --no-cache-dir
- mysql -u root < setup.sql
- ls ~/.modules/modulefiles
- cat ~/.modules/modulefiles/qiime2/2019.1
script:
- travis_wait 30 pytest --cov=mmeds -W ignore::DeprecationWarning -W ignore::FutureWarning
  -s
- tail -n 50 ~/mmeds_server_data/mmeds_log.txt
- pip uninstall mmeds -y
- sudo rm -rf ~/.modules/qiime2/var/cache
- sudo rm -rf ~/.modules/qiime1/var/cache
- sudo rm -rf ~/.modules/mmeds-stable/var/cache
- sudo find ~/.modules/ -type f -name *.pyc -delete
after_success:
- bash <(curl -s https://codecov.io/bash)
