language: python
python: "3.6"
services:
    - mysql
    - mongodb
install:
  - pip install .
  - mysql -u root < setup.sql
script:
    - pytest -s tests
    - locust -c 10 -r 10 -n 100 --no-web -f tests/locustfile.py
