language: python
python: '3.7'
dist: xenial
sudo: true
addons:
    apt:
        packages:
            - texlive-latex-base
            - texlive-latex-extra
            - texlive-latex-recommended
            - texlive-generic-recommended
            - texlive-pictures
            - texlive-publishers
            - texlive-fonts-recommended
            - texlive-fonts-extra
cache:
    directories:
        - ~/.modules/modulefiles
        - ~/.modules/qiime1
        - ~/.modules/qiime2
    timeout: 1000
    apt: true
git:
    depth: 1
services:
    - mysql
    - mongodb
    - xvfb
before_install:
    - openssl aes-256-cbc -K $encrypted_754fbe69cba7_key -iv $encrypted_754fbe69cba7_iv
      -in ./mmeds/resources/privkey.pem.enc -out ./mmeds/resources/privkey.pem -d
    - openssl aes-256-cbc -K $encrypted_ad273e68e13c_key -iv $encrypted_ad273e68e13c_iv
      -in ./mmeds/secrets.py.enc -out ./mmeds/secrets.py -d
      #- sudo apt-get install texlive-full&>/dev/null
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O ~/miniconda.sh --quiet
    - chmod +x ~/miniconda.sh
    - ~/miniconda.sh -b &>/dev/null
    - export PATH=~/miniconda2/bin:$PATH
    - conda update --yes conda &>/dev/null
    - bash travis_setup.sh
    - source ~/.bashrc
install:
    - conda info --envs
    - source activate mmeds-stable
    - pip install .
    - mysql -u root < setup.sql
script:
    - pytest --cov=mmeds -W ignore::DeprecationWarning -W ignore::FutureWarning -x
    - tail -n 200 ~/mmeds_server_data/mmeds_log.txt
    # - cd server; timeout 333 python server.py 1&>/dev/null& sleep 1; locust -c 5 -r 1 -t 5m --no-web --only-summary -f ../mmeds/tests/server_stress.py
after_success:
    - bash <(curl -s https://codecov.io/bash)
