language: python
python: '3.7'
dist: xenial
sudo: true
services:
- mysql
- mongodb
before_install:
- openssl aes-256-cbc -K $encrypted_754fbe69cba7_key -iv $encrypted_754fbe69cba7_iv
  -in ./mmeds/resources/privkey.pem.enc -out ./mmeds/resources/privkey.pem -d
- openssl aes-256-cbc -K $encrypted_ad273e68e13c_key -iv $encrypted_ad273e68e13c_iv
  -in ./mmeds/secrets.py.enc -out ./mmeds/secrets.py -d
install:
- pip install .
- mysql -u root < setup.sql
script:
- pytest --cov=./ 2> /dev/null
- cd server; timeout 333 python server.py 1&>/dev/null& sleep 1; locust -c 5 -r 1 -t 5m --no-web --only-summary -f ../mmeds/tests/server_stress.py
after_success:
- codecov
