language: python
python: '3.6'
services:
- mysql
- mongodb
install:
- pip install .
- mysql -u root < setup.sql
script:
- pytest -s tests 2> /dev/null
- cd server; timeout 333 python server.py 1&>/dev/null& sleep 1; locust -c 5 -r 1 -t 0h05m --no-web -f ../tests/server_stress.py
before_install:
- openssl aes-256-cbc -K $encrypted_754fbe69cba7_key -iv $encrypted_754fbe69cba7_iv
  -in ./server/data/privkey.pem.enc -out ./server/data/privkey.pem -d
- openssl aes-256-cbc -K $encrypted_ad273e68e13c_key -iv $encrypted_ad273e68e13c_iv
  -in ./mmeds/secrets.py.enc -out ./mmeds/secrets.py -d
