language: python
python: '3.7'
dist: xenial
sudo: true
services:
    - mysql
    - mongodb
before_install:
    - openssl aes-256-cbc -K $encrypted_754fbe69cba7_key -iv $encrypted_754fbe69cba7_iv
      -in ./mmeds/resources/privkey.pem.enc -out ./mmeds/resources/privkey.pem -d
    - openssl aes-256-cbc -K $encrypted_ad273e68e13c_key -iv $encrypted_ad273e68e13c_iv
      -in ./mmeds/secrets.py.enc -out ./mmeds/secrets.py -d
    - pwd;
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O ~/miniconda.sh
    - chmod +x ~/miniconda.sh
    - ~/miniconda.sh -b
    - export PATH=~/miniconda2/bin:$PATH
    - echo $PATH
    - conda update --yes conda
    - wget https://data.qiime2.org/distro/core/qiime2-2019.1-py36-linux-conda.yml -O ~/qiime2.yml
    - mkdir .modules
    - echo "#%Module1.0\n## qiime1 modulefile\nset curMod [module-info name]\nmodule-info name qiime1\nmodule-info version 1.9.1\nprepend-path PATH ~/anaconda3/envs/qiime1/bin" > .modules/qiime1
    - echo "#%Module1.0\n## qiime2 modulefile\nset curMod [module-info name]\nmodule-info name qiime2\nmodule-info version 2019.1\nprepend-path PATH ~/anaconda3/envs/qiime2/bin" > .modules/qiime2
    - echo "#%Module1.0\n## mmeds-stable modulefile\nset curMod [module-info name]\nmodule-info name mmeds-stable\nmodule-info version 1.5.1" > .modules/mmeds-stable
install:
    - conda create -n mmeds-stable python=3.7 --yes
    - conda create -n qiime1 python=2.7 qiime matplotlib=1.4.3 mock nose -c bioconda --yes
    - conda env create -n qiime2 --file ~/qiime2.yml
    - conda activate mmeds-stable
    - pip install .
    - mysql -u root < setup.sql
    - conda deactivate
script:
    - pytest --cov=mmeds -W ignore::DeprecationWarning -W ignore::FutureWarning 2> /dev/null
    - cd server; timeout 333 python server.py 1&>/dev/null& sleep 1; locust -c 5 -r 1 -t 5m --no-web --only-summary -f ../mmeds/tests/server_stress.py
after_success:
    - bash <(curl -s https://codecov.io/bash)
