language: python
python: '3.7'
dist: bionic
sudo: true
addons:
  apt:
    packages: libtidy5 environment-modules
before_cache:
- sudo chown -R travis:travis $HOME
- sudo chown -R travis:travis $TRAVIS_BUILD_DIR
cache:
  directories:
  - "~/.modules"
  - "~/.local"
  apt: true
after_cache:
- sudo chown -R travis:travis $HOME
- sudo chown -R travis:travis $TRAVIS_BUILD_DIR
git:
  depth: 1
services:
- mysql
- mongodb
- xvfb
before_install:
- openssl aes-256-cbc -K $encrypted_d88005e131a1_key -iv $encrypted_d88005e131a1_iv
  -in mmeds/secrets.py.enc -out mmeds/secrets.py -d
- openssl aes-256-cbc -K $encrypted_754fbe69cba7_key -iv $encrypted_754fbe69cba7_iv
  -in ./mmeds/resources/privkey.pem.enc -out ./mmeds/resources/privkey.pem -d
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O ~/miniconda.sh
  --quiet
- chmod +x ~/miniconda.sh
- "~/miniconda.sh -b &>/dev/null"
- export PATH=~/miniconda2/bin:$PATH
- conda update --yes conda &>/dev/null
- bash travis_setup.sh
- source ~/.bashrc
- conda info --envs
install:
- source activate mmeds-stable
- pip install .
- mysql --version
- mysql -u root < setup.sql | sed 's/\t/,/g' > out.csv
- cat out.csv
- mkdir ~/mmeds_server_data
- cp -r ./test_files ~/mmeds_server_data/.
script:
- coverage run ./host/manager.py&
- python ./mmeds/tests/unit/test.py
- sleep 2 # Wait for manager to terminate
- coverage combine
- bash <(curl -s https://codecov.io/bash) -cF unit
- coverage run ./host/manager.py&
- pytest --cov=mmeds -W ignore::DeprecationWarning -W ignore::FutureWarning -s ./mmeds/tests/server
  -x --durations=0
- sleep 2 # Wait for manager to terminate
- coverage combine
- mysql -u root -e "SELECT * FROM mmeds_data1.user;" > new_out.csv
- cat new_out.csv
- bash <(curl -s https://codecov.io/bash) -cF server
- pip uninstall mmeds -y
- sudo rm -rf ~/.modules/qiime2/var/cache
- sudo rm -rf ~/.modules/qiime1/var/cache
- sudo rm -rf ~/.modules/mmeds-stable/var/cache
- sudo find ~/.modules/ -type f -name *.pyc -delete
