language: python
python: '3.7'
dist: xenial
sudo: true
cache:
    directories:
        - ~/.modules
        - ~/.local
    timeout: 1000
git:
    depth: 1
services:
    - mysql
    - mongodb
before_install:
    - openssl aes-256-cbc -K $encrypted_754fbe69cba7_key -iv $encrypted_754fbe69cba7_iv
      -in ./mmeds/resources/privkey.pem.enc -out ./mmeds/resources/privkey.pem -d
    - openssl aes-256-cbc -K $encrypted_ad273e68e13c_key -iv $encrypted_ad273e68e13c_iv
      -in ./mmeds/secrets.py.enc -out ./mmeds/secrets.py -d
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O ~/miniconda.sh --quiet
    - chmod +x ~/miniconda.sh
    - ~/miniconda.sh -b &> ~/install_log.txt
    - export PATH=~/miniconda2/bin:$PATH
    - conda update --yes conda &>> ~/install_log.txt
    - echo $PATH
    - ls ~/.modules
    - ls ~/.modules/modulefiles
    - bash travis_setup.sh
install:
    - source ~/.bashrc
    - module use ~/.modules/modulefiles
    - module avail
    - conda create -n mmeds-stable python=3.7 --yes --quiet &>> install_log.txt
    - source activate mmeds-stable
    - pip install .
    - mysql -u root < setup.sql
script:
    - module use ~/.modules/modulefiles
    - module avail
    - module load qiime1
    - validate_mapping_file.py --help
    - pytest --cov=mmeds -W ignore::DeprecationWarning -W ignore::FutureWarning
    # - cd server; timeout 333 python server.py 1&>/dev/null& sleep 1; locust -c 5 -r 1 -t 5m --no-web --only-summary -f ../mmeds/tests/server_stress.py
after_success:
    - bash <(curl -s https://codecov.io/bash)
