configfile: "test_lefse_config.yaml"
report: "report.rst"

include: "../rules/common.smk"
include: "../rules/differential_abundance.smk"
include: "../rules/file_manipulation.smk"
include: "../rules/table_filtering.smk"

rule results:
    input:
        lefse_splits
