version: 1
formatters:
    default:
        format: '%(asctime)s - %(levelname)s - %(message)s'
handlers:
    console:
        class: logging.StreamHandler
        formatter: default
        level: DEBUG
    file:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: default
        maxBytes: 10485760
        backupCount: 20
        encoding: utf8
loggers:
    mmeds_logger:
        level: INFO
        handlers:
        - file
    sql_logger:
        level: DEBUG
        handlers:
        - file
