INSERT INTO `Lab` VALUES (1, 1, NULL, NULL, NULL);

INSERT INTO `SampleProtocols` VALUES (1, NULL, NULL, NULL);

INSERT INTO `RawDataProtocols` VALUES (1, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO `ResultsProtocols` VALUES (1, NULL, NULL, NULL);

INSERT INTO `IllnessBroadCategory` VALUES (1, NULL);

INSERT INTO `IllnessCategory` VALUES (1, 1, NULL);

INSERT INTO `IllnessDetails` VALUES (1, 1, NULL, NULL);

INSERT INTO `Interventions` VALUES (1, NULL, NULL, NULL);

INSERT INTO `BodySite` VALUES (1, NULL, NULL);

INSERT INTO `Type` VALUES (1, NULL, NULL);

INSERT INTO `CollectionSite` VALUES (1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO `Study` VALUES (1, 1, 1, NULL, NULL, NULL);

INSERT INTO `Experiment` VALUES (1, 1, 1, NULL);

INSERT INTO `Genotypes` VALUES (1, NULL);

INSERT INTO `Ethnicity` VALUES (1, NULL);

INSERT INTO `Subjects` VALUES (1, 1, NULL, NULL, NULL, NULL);

INSERT INTO `Heights` VALUES (1, 1, 1, NULL, NULL);

INSERT INTO `Weights` VALUES (1, 1, 1, NULL, NULL);

INSERT INTO `Illness` VALUES (1, 1, 1, 1, NULL, NULL, NULL, NULL);

INSERT INTO `Intervention` VALUES (1, 1, 1, 1, NULL, NULL, NULL);

INSERT INTO `Chow` VALUES (1, NULL, NULL, NULL);

INSERT INTO `ChowDates` VALUES (1, 1, NULL, NULL, 1);

INSERT INTO `Species` VALUES (1, NULL);

INSERT INTO `Strain` VALUES (1, NULL, NULL, NULL, 1);

INSERT INTO `Facility` VALUES (1, NULL, NULL);

INSERT INTO `Housing` VALUES (1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO `Husbandry` VALUES (1, 1, NULL, NULL, NULL, NULL);

INSERT INTO `Vendor` VALUES (1, NULL, NULL, NULL);

INSERT INTO `AnimalSubjects` VALUES (1, 1, NULL, 1, 1, 1, NULL, NULL, 1, 1, NULL);

INSERT INTO `HousingDates` VALUES (1, 1, NULL, NULL, 1, 1);

INSERT INTO `SubjectType` VALUES (1, 1, NULL, 1, 1);

INSERT INTO `Specimen` VALUES (1, 1, 1, 1, 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, 1);

INSERT INTO `Aliquot` VALUES (1, 1, 1, NULL, NULL, NULL);

INSERT INTO `SampleProtocol` VALUES (1, 1, 1, NULL, NULL, NULL, NULL);

INSERT INTO `Sample` VALUES (1, 1, 1, 1, NULL, NULL, NULL);

INSERT INTO `RawDataProtocol` VALUES (1, 1, 1, NULL, NULL, NULL);

INSERT INTO `RawData` VALUES (1, 1, 1, 1, NULL, NULL, NULL, NULL);

INSERT INTO `ResultsProtocol` VALUES (1, 1, 1, NULL, NULL, NULL);

INSERT INTO `Results` VALUES (1, 1, 1, 1, NULL, NULL);

