configfile: "test_config.yaml"
report: "report.rst"

include: "../../rules/demux_denoise.smk"
include: "../../rules/process_sequencing_data.smk"
include: "../../rules/diversity_analysis.smk"

rule results:
    input:
        expand("diversity/{metric}_group_ANOVA.qzv", metric=config['alpha_metrics']),
        expand("diversity/{metric}_{var}_PERMANOVA.qzv", metric=config['beta_metrics'], var=config['metadata'])
