# This example configuration will group data on six metadata columns,
#  and will give taxa results at the Phylum (2) and Genus (6) levels.
#  See default config file for full parameter descriptions.
sampling_depth: 1000
metadata:
  - SpecimenType
  - Ethnicity
  - IllnessStartDate
  - BirthYear
  - Sex
  - Weight
taxa_levels:
  - 2
  - 6
abundance_threshold: 0.1
font_size: 15
sub_analysis: none
additional_analysis: none
iterations: 5
permutations: 1
type: spearman
