# Sampling depth for qiime1 analysis
sampling_depth: 1000
# The metadata columns to include in analysis
# To include all columns set to 'all' (no quotes)
# Otherwise list all the column names separated by commas
# Example:
# metadata	all
metadata:
    - Ethnici
    - SpecimenBodySite
# The levels of taxa summary to include in the final summary of the analysis
taxa_levels:
    - 2
    - 3
    - 4
# The minimum abundance a taxon must have in a sample in order to be included in the legend
beta_metrics:
  - bray_curtis
alpha_metrics:
  - shannon
taxonomic_database: test
sequencing_runs: 
