# Sampling depth for qiime1 analysis
sampling_depth: 1000
# The metadata columns to include in analysis
# To include all columns set to 'all' (no quotes)
# Otherwise list all the column names separated by commas
# Example:
metadata: all
# The levels of taxa summary to include in the final summary of the analysis
taxa_levels: all
# The minimum abundance a taxon must have in a sample in order to be included in the legend
# The size of the font in the plot legends
# Columns to perform sub analysis on. 'all', 'none', or a comma seperated list
# If an additional type of analysis should be run
alpha_metrics: all
beta_metrics: all
taxonomic_database: 'test'
sequencing_runs: all

