sampling_depth: 1000
# The metadata columns to include in analysis
# To include all columns set to 'all' (no quotes)
# Otherwise list all the column names separated by commas
# Example:
# metadata	all
metadata:
  - SpecimenBodySite
  - Sex
# The levels of taxa summary to include in the final summary of the analysis
taxa_levels:
  - 2
  - 6
alpha_metrics:
  - observed_features
beta_metrics:
  - bray_curtis
taxonomic_database: test
sequencing_runs:
