-- MySQL Script generated by MySQL Workbench
-- Sat 02 Dec 2017 12:47:23 PM EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mmeds_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mmeds_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mmeds_db` DEFAULT CHARACTER SET utf8 ;
USE `mmeds_db` ;

-- -----------------------------------------------------
-- Table `mmeds_db`.`Studies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmeds_db`.`Studies` (
  `idStudies` INT NOT NULL,
  `Primary Investigator` VARCHAR(45) NULL,
  `Lab` VARCHAR(45) NULL,
  PRIMARY KEY (`idStudies`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`Subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmeds_db`.`Subjects` (
  `idSubjects` INT NOT NULL,
  PRIMARY KEY (`idSubjects`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`Samples`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmeds_db`.`Samples` (
  `idSamples` INT NOT NULL,
  `Sample Type` VARCHAR(45) NULL,
  `Subjects_idSubjects` INT NOT NULL,
  PRIMARY KEY (`idSamples`, `Subjects_idSubjects`),
  INDEX `fk_Samples_Subjects1_idx` (`Subjects_idSubjects` ASC),
  CONSTRAINT `fk_Samples_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_db`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
PACK_KEYS = DEFAULT;


-- -----------------------------------------------------
-- Table `mmeds_db`.`AnalysisTools`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmeds_db`.`AnalysisTools` (
  `idAnalysisTools` INT NOT NULL,
  `Name of Tool` VARCHAR(45) NULL,
  PRIMARY KEY (`idAnalysisTools`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`Studies_has_Samples`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmeds_db`.`Studies_has_Samples` (
  `Studies_idStudies` INT NOT NULL,
  `Samples_idSamples` INT NOT NULL,
  PRIMARY KEY (`Studies_idStudies`, `Samples_idSamples`),
  INDEX `fk_Studies_has_Samples_Samples1_idx` (`Samples_idSamples` ASC),
  INDEX `fk_Studies_has_Samples_Studies1_idx` (`Studies_idStudies` ASC),
  CONSTRAINT `fk_Studies_has_Samples_Studies1`
    FOREIGN KEY (`Studies_idStudies`)
    REFERENCES `mmeds_db`.`Studies` (`idStudies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Studies_has_Samples_Samples1`
    FOREIGN KEY (`Samples_idSamples`)
    REFERENCES `mmeds_db`.`Samples` (`idSamples`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`AnalysisTools_has_Studies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmeds_db`.`AnalysisTools_has_Studies` (
  `AnalysisTools_idAnalysisTools` INT NOT NULL,
  `Studies_idStudies` INT NOT NULL,
  PRIMARY KEY (`AnalysisTools_idAnalysisTools`, `Studies_idStudies`),
  INDEX `fk_AnalysisTools_has_Studies_Studies1_idx` (`Studies_idStudies` ASC),
  INDEX `fk_AnalysisTools_has_Studies_AnalysisTools1_idx` (`AnalysisTools_idAnalysisTools` ASC),
  CONSTRAINT `fk_AnalysisTools_has_Studies_AnalysisTools1`
    FOREIGN KEY (`AnalysisTools_idAnalysisTools`)
    REFERENCES `mmeds_db`.`AnalysisTools` (`idAnalysisTools`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AnalysisTools_has_Studies_Studies1`
    FOREIGN KEY (`Studies_idStudies`)
    REFERENCES `mmeds_db`.`Studies` (`idStudies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
