-- MySQL Script generated by MySQL Workbench
-- Tue 05 Dec 2017 10:08:52 AM EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mmeds_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mmeds_db` ;

-- -----------------------------------------------------
-- Schema mmeds_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mmeds_db` DEFAULT CHARACTER SET utf8 ;
USE `mmeds_db` ;

-- -----------------------------------------------------
-- Table `mmeds_db`.`Lab`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`Lab` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`Lab` (
  `idLab` INT NOT NULL,
  `PrimaryInvestigator` VARCHAR(45) NULL,
  PRIMARY KEY (`idLab`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`Experiment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`Experiment` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`Experiment` (
  `idLab` INT NOT NULL,
  `Lab_idLab` INT NOT NULL,
  `Experiment` VARCHAR(45) NULL,
  PRIMARY KEY (`idLab`, `Lab_idLab`),
  INDEX `fk_Experiment_Lab1_idx` (`Lab_idLab` ASC),
  CONSTRAINT `fk_Experiment_Lab1`
    FOREIGN KEY (`Lab_idLab`)
    REFERENCES `mmeds_db`.`Lab` (`idLab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`Subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`Subjects` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`Subjects` (
  `idSubjects` INT NOT NULL,
  `HostSubjectId` VARCHAR(45) NULL,
  PRIMARY KEY (`idSubjects`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`SampleType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`SampleType` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`SampleType` (
  `idSampleType` INT NOT NULL,
  `SampleType` VARCHAR(45) NULL,
  PRIMARY KEY (`idSampleType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`AnalysisTool`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`AnalysisTool` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`AnalysisTool` (
  `idAnalysisTool` INT NOT NULL,
  `AnalysisTool` VARCHAR(45) NULL,
  `RunDate` VARCHAR(45) NULL,
  PRIMARY KEY (`idAnalysisTool`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`Sample`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`Sample` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`Sample` (
  `idSample` INT NOT NULL,
  `Subjects_idSubjects` INT NOT NULL,
  `SampleType_idSampleType` INT NOT NULL,
  `AnalysisTool_idAnalysisTool` INT NOT NULL,
  `SampleID` VARCHAR(45) NULL,
  `BarcodeSequence` VARCHAR(45) NULL,
  `barcodewell` VARCHAR(45) NULL,
  `SampleDate` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`idSample`, `Subjects_idSubjects`, `SampleType_idSampleType`, `AnalysisTool_idAnalysisTool`),
  INDEX `fk_Sample_Subjects_idx` (`Subjects_idSubjects` ASC),
  INDEX `fk_Sample_SampleType1_idx` (`SampleType_idSampleType` ASC),
  INDEX `fk_Sample_AnalysisTool1_idx` (`AnalysisTool_idAnalysisTool` ASC),
  CONSTRAINT `fk_Sample_Subjects`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_db`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sample_SampleType1`
    FOREIGN KEY (`SampleType_idSampleType`)
    REFERENCES `mmeds_db`.`SampleType` (`idSampleType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sample_AnalysisTool1`
    FOREIGN KEY (`AnalysisTool_idAnalysisTool`)
    REFERENCES `mmeds_db`.`AnalysisTool` (`idAnalysisTool`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`Experiment_has_Subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`Experiment_has_Subjects` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`Experiment_has_Subjects` (
  `Experiment_idLab` INT NOT NULL,
  `Subjects_idSubjects` INT NOT NULL,
  PRIMARY KEY (`Experiment_idLab`, `Subjects_idSubjects`),
  INDEX `fk_Experiment_has_Subjects_Subjects1_idx` (`Subjects_idSubjects` ASC),
  INDEX `fk_Experiment_has_Subjects_Experiment1_idx` (`Experiment_idLab` ASC),
  CONSTRAINT `fk_Experiment_has_Subjects_Experiment1`
    FOREIGN KEY (`Experiment_idLab`)
    REFERENCES `mmeds_db`.`Experiment` (`idLab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Experiment_has_Subjects_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_db`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
