-- MySQL Script generated by MySQL Workbench
-- Mon 05 Mar 2018 08:34:38 AM EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mmeds_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mmeds_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mmeds_db` DEFAULT CHARACTER SET utf8 ;
USE `mmeds_db` ;

-- -----------------------------------------------------
-- Table `mmeds_db`.`Lab`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`Lab` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`Lab` (
  `idLab` INT NOT NULL,
  `PrimaryInvestigator` VARCHAR(45) NULL DEFAULT NULL,
  `ContactEmail` VARCHAR(45) NULL DEFAULT NULL,
  `ContactName` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idLab`))
ENGINE = InnoDB
COMMENT = 'Additional field for contact person. defaults to PI';


-- -----------------------------------------------------
-- Table `mmeds_db`.`Study`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`Study` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`Study` (
  `idStudy` INT NOT NULL,
  `Lab_idLab` INT NOT NULL,
  `Experiment` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idStudy`, `Lab_idLab`),
  INDEX `fk_Experiment_Lab1_idx` (`Lab_idLab` ASC),
  CONSTRAINT `fk_Experiment_Lab1`
    FOREIGN KEY (`Lab_idLab`)
    REFERENCES `mmeds_db`.`Lab` (`idLab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`Subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`Subjects` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`Subjects` (
  `idSubjects` INT NOT NULL,
  `HostSubjectId` VARCHAR(45) NULL DEFAULT NULL,
  `Nationality_idNationality` VARCHAR(8) NULL DEFAULT NULL,
  `Sex_idSex` INT NULL DEFAULT NULL,
  `Age` VARCHAR(45) NULL DEFAULT NULL,
  `Height` VARCHAR(45) NULL DEFAULT NULL,
  `Weight` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idSubjects`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`Type` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`Type` (
  `idType` INT NOT NULL,
  `SpecimenType` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`Location` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`Location` (
  `idLocation` INT NOT NULL,
  `Latitude` FLOAT NULL DEFAULT NULL,
  `Longitude` FLOAT NULL DEFAULT NULL,
  `Depth` FLOAT NULL DEFAULT NULL,
  `Elevation` FLOAT NULL DEFAULT NULL,
  `(E) Feature` VARCHAR(45) NULL DEFAULT NULL,
  `(E) Biome` VARCHAR(45) NULL DEFAULT NULL,
  `(E) Material` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idLocation`))
ENGINE = InnoDB
COMMENT = 'Change to collection site. Add field for collection_tech or similar';


-- -----------------------------------------------------
-- Table `mmeds_db`.`BodySite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`BodySite` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`BodySite` (
  `idBodySite` INT NOT NULL,
  `SpecimenBodySite` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idBodySite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`Specimen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`Specimen` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`Specimen` (
  `idSpecimen` INT NOT NULL,
  `Subjects_idSubjects` INT NOT NULL,
  `SampleType_idSampleType` INT NOT NULL,
  `Location_idLocation` INT NOT NULL,
  `BodySite_idBodySite` INT NOT NULL,
  `SampleID` VARCHAR(45) NULL DEFAULT NULL,
  `BarcodeSequence` VARCHAR(45) NULL DEFAULT NULL,
  `BarcodeWell` VARCHAR(45) NULL DEFAULT NULL,
  `SampleDate` DATETIME NULL DEFAULT NULL,
  `Description` VARCHAR(45) NULL DEFAULT NULL,
  `AdditionalInformation` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idSpecimen`, `Subjects_idSubjects`, `SampleType_idSampleType`, `Location_idLocation`, `BodySite_idBodySite`),
  INDEX `fk_Sample_Subjects_idx` (`Subjects_idSubjects` ASC),
  INDEX `fk_Sample_SampleType1_idx` (`SampleType_idSampleType` ASC),
  INDEX `fk_Sample_Location1_idx` (`Location_idLocation` ASC),
  INDEX `fk_Specimen_BodySite1_idx` (`BodySite_idBodySite` ASC),
  CONSTRAINT `fk_Sample_Subjects`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_db`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sample_SampleType1`
    FOREIGN KEY (`SampleType_idSampleType`)
    REFERENCES `mmeds_db`.`Type` (`idType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sample_Location1`
    FOREIGN KEY (`Location_idLocation`)
    REFERENCES `mmeds_db`.`Location` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specimen_BodySite1`
    FOREIGN KEY (`BodySite_idBodySite`)
    REFERENCES `mmeds_db`.`BodySite` (`idBodySite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Add table for body site 1:n';


-- -----------------------------------------------------
-- Table `mmeds_db`.`Experiment_has_Subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`Experiment_has_Subjects` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`Experiment_has_Subjects` (
  `Experiment_idLab` INT NOT NULL,
  `Subjects_idSubjects` INT NOT NULL,
  PRIMARY KEY (`Experiment_idLab`, `Subjects_idSubjects`),
  INDEX `fk_Experiment_has_Subjects_Subjects1_idx` (`Subjects_idSubjects` ASC),
  INDEX `fk_Experiment_has_Subjects_Experiment1_idx` (`Experiment_idLab` ASC),
  CONSTRAINT `fk_Experiment_has_Subjects_Experiment1`
    FOREIGN KEY (`Experiment_idLab`)
    REFERENCES `mmeds_db`.`Study` (`idStudy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Experiment_has_Subjects_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_db`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`Ethnicity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`Ethnicity` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`Ethnicity` (
  `idEthnicity` INT NOT NULL,
  `Ethnicity` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idEthnicity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`Subjects_has_Ethnicity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`Subjects_has_Ethnicity` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`Subjects_has_Ethnicity` (
  `Subjects_idSubjects` INT NOT NULL,
  `Ethnicity_idEthnicity` INT NOT NULL,
  PRIMARY KEY (`Subjects_idSubjects`, `Ethnicity_idEthnicity`),
  INDEX `fk_Subjects_has_Ethnicity_Ethnicity1_idx` (`Ethnicity_idEthnicity` ASC),
  INDEX `fk_Subjects_has_Ethnicity_Subjects1_idx` (`Subjects_idSubjects` ASC),
  CONSTRAINT `fk_Subjects_has_Ethnicity_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_db`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subjects_has_Ethnicity_Ethnicity1`
    FOREIGN KEY (`Ethnicity_idEthnicity`)
    REFERENCES `mmeds_db`.`Ethnicity` (`idEthnicity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`Illnesses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`Illnesses` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`Illnesses` (
  `idIllnesses` INT NOT NULL,
  `Illnesses_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idIllnesses`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`Illness`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`Illness` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`Illness` (
  `idIllness` INT NOT NULL,
  `StartDate` DATETIME NULL DEFAULT NULL,
  `EndDate` DATETIME NULL DEFAULT NULL,
  `Subjects_idSubjects` INT NOT NULL,
  `Illnesses_idIllnesses` INT NOT NULL,
  PRIMARY KEY (`idIllness`, `Subjects_idSubjects`, `Illnesses_idIllnesses`),
  INDEX `fk_Illness_Subjects1_idx` (`Subjects_idSubjects` ASC),
  INDEX `fk_Illness_Illnesses1_idx` (`Illnesses_idIllnesses` ASC),
  CONSTRAINT `fk_Illness_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_db`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Illness_Illnesses1`
    FOREIGN KEY (`Illnesses_idIllnesses`)
    REFERENCES `mmeds_db`.`Illnesses` (`idIllnesses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`Interventions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`Interventions` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`Interventions` (
  `idIntervention` INT NOT NULL,
  `Additional_information` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idIntervention`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`Intervention`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`Intervention` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`Intervention` (
  `idIntervention` INT NOT NULL,
  `StartDate` DATETIME NULL DEFAULT NULL,
  `EndDate` DATETIME NULL DEFAULT NULL,
  `Subjects_idSubjects` INT NOT NULL,
  `Interventions_idIntervention` INT NOT NULL,
  PRIMARY KEY (`idIntervention`, `Subjects_idSubjects`, `Interventions_idIntervention`),
  INDEX `fk_Treatment_Subjects1_idx` (`Subjects_idSubjects` ASC),
  INDEX `fk_Intervention_Interventions1_idx` (`Interventions_idIntervention` ASC),
  CONSTRAINT `fk_Treatment_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_db`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Intervention_Interventions1`
    FOREIGN KEY (`Interventions_idIntervention`)
    REFERENCES `mmeds_db`.`Interventions` (`idIntervention`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Reduce to intervention which links to interventions table. Some interventions are treatments';


-- -----------------------------------------------------
-- Table `mmeds_db`.`Aliquot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`Aliquot` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`Aliquot` (
  `idAliquot` INT NOT NULL,
  `Specimen_idSpecimen` INT NOT NULL,
  `Specimen_Subjects_idSubjects` INT NOT NULL,
  `Specimen_SampleType_idSampleType` INT NOT NULL,
  `Specimen_Location_idLocation` INT NOT NULL,
  `Specimen_BodySite_idBodySite` INT NOT NULL,
  PRIMARY KEY (`idAliquot`, `Specimen_idSpecimen`, `Specimen_Subjects_idSubjects`, `Specimen_SampleType_idSampleType`, `Specimen_Location_idLocation`, `Specimen_BodySite_idBodySite`),
  INDEX `fk_Aliquot_Specimen1_idx` (`Specimen_idSpecimen` ASC, `Specimen_Subjects_idSubjects` ASC, `Specimen_SampleType_idSampleType` ASC, `Specimen_Location_idLocation` ASC, `Specimen_BodySite_idBodySite` ASC),
  CONSTRAINT `fk_Aliquot_Specimen1`
    FOREIGN KEY (`Specimen_idSpecimen` , `Specimen_Subjects_idSubjects` , `Specimen_SampleType_idSampleType` , `Specimen_Location_idLocation` , `Specimen_BodySite_idBodySite`)
    REFERENCES `mmeds_db`.`Specimen` (`idSpecimen` , `Subjects_idSubjects` , `SampleType_idSampleType` , `Location_idLocation` , `BodySite_idBodySite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`SampleProtocols`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`SampleProtocols` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`SampleProtocols` (
  `idTools` INT NOT NULL,
  `ToolName` VARCHAR(45) NULL DEFAULT NULL,
  `Version` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idTools`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`SampleProtocol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`SampleProtocol` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`SampleProtocol` (
  `idSampleProtocol` INT NOT NULL,
  `DatePerformed` DATETIME NULL DEFAULT NULL,
  `Processor` VARCHAR(45) NULL DEFAULT NULL,
  `SampleProtocols_idTools` INT NOT NULL,
  PRIMARY KEY (`idSampleProtocol`, `SampleProtocols_idTools`),
  INDEX `fk_SampleProtocol_SampleProtocols1_idx` (`SampleProtocols_idTools` ASC),
  CONSTRAINT `fk_SampleProtocol_SampleProtocols1`
    FOREIGN KEY (`SampleProtocols_idTools`)
    REFERENCES `mmeds_db`.`SampleProtocols` (`idTools`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`Sample`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`Sample` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`Sample` (
  `idSample` INT NOT NULL,
  `SampleProtocol_idSampleProtocol` INT NOT NULL,
  `SampleProtocol_SampleProtocols_idTools` INT NOT NULL,
  `Aliquot_idAliquot` INT NOT NULL,
  `Aliquot_Specimen_idSpecimen` INT NOT NULL,
  `Aliquot_Specimen_Subjects_idSubjects` INT NOT NULL,
  `Aliquot_Specimen_SampleType_idSampleType` INT NOT NULL,
  `Aliquot_Specimen_Location_idLocation` INT NOT NULL,
  `Aliquot_Specimen_BodySite_idBodySite` INT NOT NULL,
  PRIMARY KEY (`idSample`, `SampleProtocol_idSampleProtocol`, `SampleProtocol_SampleProtocols_idTools`, `Aliquot_idAliquot`, `Aliquot_Specimen_idSpecimen`, `Aliquot_Specimen_Subjects_idSubjects`, `Aliquot_Specimen_SampleType_idSampleType`, `Aliquot_Specimen_Location_idLocation`, `Aliquot_Specimen_BodySite_idBodySite`),
  INDEX `fk_Sample_SampleProtocol1_idx` (`SampleProtocol_idSampleProtocol` ASC, `SampleProtocol_SampleProtocols_idTools` ASC),
  INDEX `fk_Sample_Aliquot1_idx` (`Aliquot_idAliquot` ASC, `Aliquot_Specimen_idSpecimen` ASC, `Aliquot_Specimen_Subjects_idSubjects` ASC, `Aliquot_Specimen_SampleType_idSampleType` ASC, `Aliquot_Specimen_Location_idLocation` ASC, `Aliquot_Specimen_BodySite_idBodySite` ASC),
  CONSTRAINT `fk_Sample_SampleProtocol1`
    FOREIGN KEY (`SampleProtocol_idSampleProtocol` , `SampleProtocol_SampleProtocols_idTools`)
    REFERENCES `mmeds_db`.`SampleProtocol` (`idSampleProtocol` , `SampleProtocols_idTools`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sample_Aliquot1`
    FOREIGN KEY (`Aliquot_idAliquot` , `Aliquot_Specimen_idSpecimen` , `Aliquot_Specimen_Subjects_idSubjects` , `Aliquot_Specimen_SampleType_idSampleType` , `Aliquot_Specimen_Location_idLocation` , `Aliquot_Specimen_BodySite_idBodySite`)
    REFERENCES `mmeds_db`.`Aliquot` (`idAliquot` , `Specimen_idSpecimen` , `Specimen_Subjects_idSubjects` , `Specimen_SampleType_idSampleType` , `Specimen_Location_idLocation` , `Specimen_BodySite_idBodySite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`RawDataProtocols`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`RawDataProtocols` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`RawDataProtocols` (
  `RawDataProtocols` INT NOT NULL,
  `RawDataProtocolscol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`RawDataProtocols`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`RawDataProtocol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`RawDataProtocol` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`RawDataProtocol` (
  `idRawDataProtocols` INT NOT NULL,
  `DatePerformed` DATETIME NULL DEFAULT NULL,
  `Processor` VARCHAR(45) NULL DEFAULT NULL,
  `RawDataProtocols_RawDataProtocols` INT NOT NULL,
  PRIMARY KEY (`idRawDataProtocols`, `RawDataProtocols_RawDataProtocols`),
  INDEX `fk_RawDataProtocols_RawDataProtocols1_idx` (`RawDataProtocols_RawDataProtocols` ASC),
  CONSTRAINT `fk_RawDataProtocols_RawDataProtocols1`
    FOREIGN KEY (`RawDataProtocols_RawDataProtocols`)
    REFERENCES `mmeds_db`.`RawDataProtocols` (`RawDataProtocols`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`RawData`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`RawData` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`RawData` (
  `idRawData` INT NOT NULL,
  `Sample_idSample` INT NOT NULL,
  `DateCreated` DATETIME NULL DEFAULT NULL,
  `RawDataProtocols_idRawDataProtocols` INT NOT NULL,
  `RawDataProtocols_RawDataProtocols_RawDataProtocols` INT NOT NULL,
  PRIMARY KEY (`idRawData`, `Sample_idSample`, `RawDataProtocols_idRawDataProtocols`, `RawDataProtocols_RawDataProtocols_RawDataProtocols`),
  INDEX `fk_rawData_Sample1_idx` (`Sample_idSample` ASC),
  INDEX `fk_rawData_RawDataProtocols1_idx` (`RawDataProtocols_idRawDataProtocols` ASC, `RawDataProtocols_RawDataProtocols_RawDataProtocols` ASC),
  CONSTRAINT `fk_rawData_Sample1`
    FOREIGN KEY (`Sample_idSample`)
    REFERENCES `mmeds_db`.`Sample` (`idSample`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rawData_RawDataProtocols1`
    FOREIGN KEY (`RawDataProtocols_idRawDataProtocols` , `RawDataProtocols_RawDataProtocols_RawDataProtocols`)
    REFERENCES `mmeds_db`.`RawDataProtocol` (`idRawDataProtocols` , `RawDataProtocols_RawDataProtocols`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`ResultsProtocols`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`ResultsProtocols` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`ResultsProtocols` (
  `idResultsProtocols` INT NOT NULL,
  `ResultsProtocolscol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idResultsProtocols`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`ResultsProtocol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`ResultsProtocol` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`ResultsProtocol` (
  `idResultsProtocols` INT NOT NULL,
  `DatePerformed` DATETIME NULL DEFAULT NULL,
  `Processor` VARCHAR(45) NULL DEFAULT NULL,
  `ResultsProtocols_idResultsProtocols` INT NOT NULL,
  PRIMARY KEY (`idResultsProtocols`, `ResultsProtocols_idResultsProtocols`),
  INDEX `fk_ResultsProtocols_ResultsProtocols1_idx` (`ResultsProtocols_idResultsProtocols` ASC),
  CONSTRAINT `fk_ResultsProtocols_ResultsProtocols1`
    FOREIGN KEY (`ResultsProtocols_idResultsProtocols`)
    REFERENCES `mmeds_db`.`ResultsProtocols` (`idResultsProtocols`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`Results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`Results` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`Results` (
  `idResults` INT NOT NULL,
  `dry_analysis` INT NOT NULL,
  `rawData_Sample_idSample` INT NOT NULL,
  `DateCreated` DATETIME NULL DEFAULT NULL,
  `ResultsProtocols_idResultsProtocols` INT NOT NULL,
  `ResultsProtocols_ResultsProtocols_idResultsProtocols` INT NOT NULL,
  PRIMARY KEY (`idResults`, `dry_analysis`, `rawData_Sample_idSample`, `ResultsProtocols_idResultsProtocols`, `ResultsProtocols_ResultsProtocols_idResultsProtocols`),
  INDEX `fk_Results_rawData1_idx` (`dry_analysis` ASC, `rawData_Sample_idSample` ASC),
  INDEX `fk_Results_ResultsProtocols1_idx` (`ResultsProtocols_idResultsProtocols` ASC, `ResultsProtocols_ResultsProtocols_idResultsProtocols` ASC),
  CONSTRAINT `fk_Results_rawData1`
    FOREIGN KEY (`dry_analysis` , `rawData_Sample_idSample`)
    REFERENCES `mmeds_db`.`RawData` (`idRawData` , `Sample_idSample`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Results_ResultsProtocols1`
    FOREIGN KEY (`ResultsProtocols_idResultsProtocols` , `ResultsProtocols_ResultsProtocols_idResultsProtocols`)
    REFERENCES `mmeds_db`.`ResultsProtocol` (`idResultsProtocols` , `ResultsProtocols_idResultsProtocols`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`Genotypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`Genotypes` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`Genotypes` (
  `idGenotypes` INT NOT NULL,
  `Genotypescol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idGenotypes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`Subjects_has_Genotypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`Subjects_has_Genotypes` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`Subjects_has_Genotypes` (
  `Subjects_idSubjects` INT NOT NULL,
  `Genotypes_idGenotypes` INT NOT NULL,
  PRIMARY KEY (`Subjects_idSubjects`, `Genotypes_idGenotypes`),
  INDEX `fk_Subjects_has_Genotypes_Genotypes1_idx` (`Genotypes_idGenotypes` ASC),
  INDEX `fk_Subjects_has_Genotypes_Subjects1_idx` (`Subjects_idSubjects` ASC),
  CONSTRAINT `fk_Subjects_has_Genotypes_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_db`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subjects_has_Genotypes_Genotypes1`
    FOREIGN KEY (`Genotypes_idGenotypes`)
    REFERENCES `mmeds_db`.`Genotypes` (`idGenotypes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
