-- MySQL Script generated by MySQL Workbench
-- Mon 04 Dec 2017 10:22:47 AM EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mmeds_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mmeds_db` ;

-- -----------------------------------------------------
-- Schema mmeds_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mmeds_db` DEFAULT CHARACTER SET utf8 ;
USE `mmeds_db` ;

-- -----------------------------------------------------
-- Table `mmeds_db`.`Studies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`Studies` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`Studies` (
  `idStudies` INT NOT NULL,
  `Lab` VARCHAR(45) NULL,
  `PrimaryInvestigator` VARCHAR(45) NULL,
  PRIMARY KEY (`idStudies`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`Subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`Subjects` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`Subjects` (
  `idSubjects` INT NOT NULL,
  `HostSubjectId` INT NULL,
  PRIMARY KEY (`idSubjects`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`Samples`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`Samples` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`Samples` (
  `idSamples` INT NOT NULL,
  `Subjects_idSubjects` INT NOT NULL,
  `SampleType` VARCHAR(45) NULL,
  `BarcodeSequence` VARCHAR(45) NULL,
  `LinkerPrimerSequence` VARCHAR(45) NULL,
  `SampleID` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`idSamples`))
ENGINE = InnoDB
PACK_KEYS = DEFAULT;

CREATE INDEX `fk_Samples_Subjects1_idx` ON `mmeds_db`.`Samples` (`Subjects_idSubjects` ASC);


-- -----------------------------------------------------
-- Table `mmeds_db`.`AnalysisTools`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`AnalysisTools` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`AnalysisTools` (
  `idAnalysisTools` INT NOT NULL,
  `NameOfTool` VARCHAR(45) NULL,
  `RunDate` DATE NULL,
  PRIMARY KEY (`idAnalysisTools`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_db`.`AnalysisTools_has_Studies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`AnalysisTools_has_Studies` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`AnalysisTools_has_Studies` (
  `AnalysisTools_idAnalysisTools` INT NOT NULL,
  `Studies_idStudies` INT NOT NULL,
  PRIMARY KEY (`AnalysisTools_idAnalysisTools`, `Studies_idStudies`))
ENGINE = InnoDB;

CREATE INDEX `fk_AnalysisTools_has_Studies_Studies1_idx` ON `mmeds_db`.`AnalysisTools_has_Studies` (`Studies_idStudies` ASC);

CREATE INDEX `fk_AnalysisTools_has_Studies_AnalysisTools1_idx` ON `mmeds_db`.`AnalysisTools_has_Studies` (`AnalysisTools_idAnalysisTools` ASC);


-- -----------------------------------------------------
-- Table `mmeds_db`.`Studies_has_Subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_db`.`Studies_has_Subjects` ;

CREATE TABLE IF NOT EXISTS `mmeds_db`.`Studies_has_Subjects` (
  `Studies_idStudies` INT NOT NULL,
  `Subjects_idSubjects` INT NOT NULL,
  PRIMARY KEY (`Studies_idStudies`, `Subjects_idSubjects`))
ENGINE = InnoDB;

CREATE INDEX `fk_Studies_has_Subjects_Subjects1_idx` ON `mmeds_db`.`Studies_has_Subjects` (`Subjects_idSubjects` ASC);

CREATE INDEX `fk_Studies_has_Subjects_Studies1_idx` ON `mmeds_db`.`Studies_has_Subjects` (`Studies_idStudies` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
