from mmeds.server import MMEDSserver
from time import time, sleep
from collections import defaultdict
from pathlib import Path
from tidylib import tidy_document
from tempfile import gettempdir

import mmeds.config as fig
import mmeds.secrets as sec
import mmeds.error as err
from mmeds.authentication import add_user, remove_user
from mmeds.util import recieve_email, send_email
from mmeds.spawn import Watcher
from mmeds.logging import Logger

import cherrypy as cp
import re
from cherrypy.test import helper


testing = True
monitor = Watcher()
monitor.connect()
server = MMEDSserver()
pipe = monitor.get_pipe()
queue = monitor.get_queue()


def check_page(page):
    """ Checks that no errors were generated by the html """
    document, errors = tidy_document(page)
    all_errors = errors.split('\n')
    for error in all_errors:
        # Make sure there are only warnings
        assert 'error' not in error


class TestServer(helper.CPWebCase):

    server_code = 'server_code_' + fig.get_salt(10)
    # Create a unique user id from the current time
    server_user = fig.SERVER_USER + fig.get_salt(10)  # str(int(time()))
    access_code = None
    lab_user = 'lab_user_' + str(int(time()))
    tp = None

    ##################
    # Helper Methods #
    ##################

    def assertBody(self, check_body):
        """
        Override this assert for logging purposes
        Write both pages to a tempfile for easy comparison
        """
        bad_page = Path(gettempdir()) / 'bad_page.html'
        bad_page.touch()
        bad_page.write_bytes(self.body)

        good_page = Path(gettempdir()) / 'good_page.html'
        good_page.touch()
        if isinstance(check_body, str):
            good_page.write_text(check_body)
        else:
            good_page.write_bytes(check_body)
        super().assertBody(check_body)

    def upload_files(self, file_handles, file_paths, file_types):
        """ Helper method to setup headers and body for uploading a file """
        boundry = fig.get_salt(10)
        zipped = zip(file_handles, file_paths, file_types)
        b = b''
        for file_handle, file_path, file_type in zipped:
            # Byte strings
            b += str.encode('--{}\r\n'.format(boundry) +
                            'Content-Disposition: form-data; name="{}"; '.format(file_handle))
            # IF the file_type is '' treat it as a string param
            if file_type == '':
                b += str.encode('\r\n\r\n{}\r\n'.format(file_path))
            # Otherwise load the file
            else:
                b += str.encode('filename="{}"\r\n'.format(Path(file_path).name) +
                                'Content-Type: {}\r\n\r\n'.format(file_type))
                if not file_path == '':
                    b += Path(file_path).read_bytes() + str.encode('\r\n')
            b + str.encode('\r\n')
        b += str.encode('--{}--\r\n'.format(boundry))

        filesize = len(b)
        h = [('Content-Type', 'multipart/form-data; boundary={}'.format(boundry)),
             ('Content-Length', str(filesize)),
             ('Connection', 'keep-alive')]
        return h, b

    @staticmethod
    def setup_server():
        test_config = defaultdict(dict)
        test_config['global']['tools.sessions.on'] = True
        test_config['global']['tools.sessions.name'] = 'cp_session'
        cp.config.update(test_config)
        cp.tree.mount(server)

    def test_aa_setup(self):
        Logger.info('===== Test Server Start =====')
        add_user(self.lab_user, sec.TEST_PASS, fig.TEST_EMAIL, 1, True)

    def test_ab_index(self):
        Logger.info('ab index')
        self.getPage('/index')
        self.assertStatus('200 OK')
        self.assertHeader('Content-Type', 'text/html;charset=utf-8')
        page_body = self.body.decode('utf-8')
        check_page(page_body)
        self.getPage('/auth/public_guide')
        self.assertStatus('200 OK')

    def test_ba_sign_up(self):
        Logger.info('ba sign up')
        self.not_logged_in()
        self.sign_up_fail()
        self.sign_up_success()

    def test_bc_login(self):
        Logger.info('bc login')
        self.login_fail_password()
        self.login_fail_username()
        self.login()
        self.logout()

    def test_bd_reset_password(self):
        Logger.info('bd reset password')
        self.tp = self.reset_password()
        self.login(True)
        self.change_password()
        self.logout()

    def test_ca_animal_upload(self):
        Logger.info('ca animal upload')
        self.login()
        self.upload_animal_metadata()
        self.upload_otu_data()
        self.logout()

    def test_cb_upload(self):
        Logger.info('cb upload')
        self.login()
        self.upload_metadata_fail()
        self.upload_metadata()
        self.upload_data()
        self.modify_upload()
        self.logout()

    def test_cc_lefse_upload(self):
        return
        self.login()
        self.upload_lefse()
        self.logout()

    def test_cd_dual_upload(self):
        return
        self.login()
        self.upload_dualBarcode_metadata()

    def test_da_select_study(self):
        Logger.info('da view study')
        self.login()
        self.select_study()
        self.logout()

    def test_da_download(self):
        Logger.info('da download')
        self.login()
        self.download_page_fail()
        self.download()
        self.logout()

    def test_db_download(self):
        return
        self.login()
        self.convert()
        self.lab_download()
        self.user_download()
        self.logout()

    def test_ea_analysis_no_privileges(self):
        self.login()
        self.check_analysis_no_privileges()
        self.logout()

    def test_eb_analysis_has_privileges(self):
        self.login(lab=True)
        self.check_analysis_has_privileges()
        self.logout()

    def test_ec_run_analysis(self):
        self.login()
        self.run_test_analysis()
        self.view_analysis()
        self.logout()

    def test_y_query(self):
        return
        self.login()
        self.execute_invalid_query()
        self.execute_protected_query()
        self.execute_query()

    def test_z_cleanup(self):
        remove_user(self.server_user, testing=testing)
        remove_user(self.lab_user, testing=testing)
        # Send an email at the end to ensure there aren't issues with
        # accessing the correct email in future test runs
        send_email(fig.TEST_EMAIL, 'tester', 'error', testing=testing)
        queue.put(('terminate'))
        Logger.error('Waiting on pipe')
        result = pipe.recv()
        while not result == 'Watcher exiting':
            result = pipe.recv()
        Logger.error('Got {} from pipe'.format(result))
        self.assertEqual(result, 'Watcher exiting')

    ####################
    #  Authentication  #
    ####################

    def not_logged_in(self):
        """ Check that trying to upload while not logged in takes you to the homepage """
        self.getPage('/index')
        self.assertStatus('200 OK')

        home_page = self.body

        self.getPage('/upload/upload_page')

        self.assertBody(home_page)

    def sign_up_fail(self):
        """ Check a unsuccessful sign in """
        # Check the sign up input page
        self.getPage('/auth/register_account')
        self.assertStatus('200 OK')

        addr = '/auth/sign_up?username={}&email={}&password1={}&password2={}'

        # Test signup with an invalid username
        faddr = addr.format('public', fig.TEST_EMAIL, sec.TEST_PASS, sec.TEST_PASS)
        self.getPage(faddr)
        self.assertStatus('200 OK')
        bad_page = server.load_webpage('auth_sign_up_page', error='Username is invalid.')
        self.assertBody(bad_page)

        # Test signup with an invalid password
        self.getPage(addr.format(self.server_user, fig.TEST_EMAIL, sec.TEST_PASS, sec.TEST_PASS + 'xx'))
        self.assertStatus('200 OK')
        bad_page = server.load_webpage('auth_sign_up_page', error=['Passwords do not match.'])
        self.assertBody(bad_page)

        Logger.debug('continuing sign up')

    def sign_up_success(self):
        """ Check a successful sign in """
        addr = '/auth/sign_up?username={}&email={}&password1={}&password2={}'

        # Test successful signup
        self.getPage(addr.format(self.server_user, fig.TEST_EMAIL, sec.TEST_PASS, sec.TEST_PASS))
        self.assertStatus('200 OK')
        good_page = server.load_webpage('login', success='Account created successfully!')
        self.assertBody(good_page)

    def login(self, alt=False, lab=False):
        """ When alt is True use alternate password """
        account_log = Path(gettempdir()) / 'account_log.txt'
        if lab:
            account_log.write_text('{}\t{}\t{}'.format(self.lab_user, sec.TEST_PASS, alt))
            self.getPage('/login?username={}&password={}'.format(self.lab_user, sec.TEST_PASS))
            user = self.lab_user
        elif alt:
            account_log.write_text('{}\t{}\t{}'.format(self.server_user, self.tp, alt))
            self.getPage('/login?username={}&password={}'.format(self.server_user, self.tp))
            user = self.server_user
        else:
            account_log.write_text('{}\t{}\t{}'.format(self.server_user, sec.TEST_PASS, alt))
            self.getPage('/login?username={}&password={}'.format(self.server_user, sec.TEST_PASS))
            user = self.server_user
        self.assertStatus('200 OK')
        page = server.load_webpage('home', user=user, dir='.')
        self.assertBody(page)

    def logout(self):
        self.getPage('/login?username={}&password={}'.format(self.server_user, sec.TEST_PASS))
        self.getPage('/auth/logout', headers=self.cookies)
        page = server.load_webpage('login')
        self.assertBody(page)

    def login_fail_password(self):
        self.getPage('/login?username={}&password={}'.format(self.server_user, sec.TEST_PASS + 'garbage'))
        self.assertStatus('200 OK')
        page = server.load_webpage('login', error=err.InvalidLoginError().message)
        self.assertBody(page)

    def login_fail_username(self):
        self.getPage('/login?username={}&password={}'.format(self.server_user + 'garbage', sec.TEST_PASS))
        self.assertStatus('200 OK')
        page = server.load_webpage('login', error=err.InvalidLoginError().message)
        self.assertBody(page)

    def reset_password(self):
        Logger.debug('reset_password')
        self.getPage('/auth/submit_password_recovery?username={}&email={}'.format(self.server_user,
                                                                                  fig.TEST_EMAIL + 'dfa'))
        self.assertStatus('200 OK')
        fail_page = server.load_webpage('login', error='No account exists with the provided username and email.')
        self.assertBody(fail_page)

        self.getPage('/auth/submit_password_recovery?username={}&email={}'.format(self.server_user, fig.TEST_EMAIL))
        self.assertStatus('200 OK')
        pass_page = server.load_webpage('login', success='A new password has been sent to your email.')
        self.assertBody(pass_page)

        mail = recieve_email(self.server_user, 'reset', 'Your password has been reset.')
        new_pass = mail.split('password is:')[1].splitlines()[1].strip()
        return new_pass

    def change_password(self):
        Logger.debug('change_password')
        self.getPage('/login?username={}&password={}'.format(self.server_user, self.tp))
        self.assertStatus('200 OK')
        self.getPage('/auth/input_password', self.cookies)
        self.assertStatus('200 OK')
        temp_pass_bad = 'thi$1sT'
        self.getPage('/auth/change_password?password0={old}&password1={new}&password2={new}'.format(old=self.tp,
                                                                                                    new=temp_pass_bad),
                     self.cookies)
        self.assertStatus('200 OK')
        fail_page = server.load_webpage('auth_change_password',
                                        user=self.server_user,
                                        account_selected='w3-text-blue',
                                        home_selected='',
                                        error=['Passwords must be longer than 10 characters.'])

        self.assertBody(fail_page)
        self.getPage('/auth/change_password?password0={old}&password1={new}&password2={new}'.format(old=self.tp,
                                                                                                    new=sec.TEST_PASS),
                     self.cookies)
        self.assertStatus('200 OK')
        pass_page = server.load_webpage('auth_change_password',
                                        user=self.server_user,
                                        account_selected='w3-text-blue',
                                        home_selected='',
                                        success='Your password was successfully changed.')
        self.assertBody(pass_page)

        self.getPage('/login?username={}&password={}'.format(self.server_user, sec.TEST_PASS))
        self.assertStatus('200 OK')

    ###########
    # Uploads #
    ###########

    def upload_animal_metadata(self):
        """ Try uploading the two metadata files associated with animal metadata """
        self.getPage('/upload/upload_page', self.cookies)
        self.assertStatus('200 OK')

        # Check an invalid metadata filetype
        self.getPage('/upload/upload_metadata?uploadType=sparcc&studyName=Good_Study&subjectType=animal',
                     self.cookies)
        self.assertStatus('200 OK')

        headers, body = self.upload_files(['myMetaData'], [fig.TEST_ANIMAL_SUBJECT], ['text/tab-seperated-values'])
        self.getPage('/upload/validate_metadata?barcodes_type=None', headers + self.cookies, 'POST', body)
        self.assertStatus('200 OK')

        headers, body = self.upload_files(['myMetaData'], [fig.TEST_SPECIMEN], ['text/tab-seperated-values'])
        self.getPage('/upload/validate_metadata?barcodes_type=other', headers + self.cookies, 'POST', body)
        self.assertStatus('200 OK')
        page_body = self.body
        document, errors = tidy_document(page_body)
        # Assert no errors, warnings are okay
        for warn in errors:
            assert not ('error' in warn or 'Error' in warn)

    def upload_otu_data(self):
        """ Try uploading an otu data file """
        self.getPage('/upload/upload_data', self.cookies)
        self.assertStatus('200 OK')

        headers, body = self.upload_files(['otu_table'], [fig.TEST_OTU], ['text/tab-seperated-values'])
        self.getPage('/upload/process_data', headers + self.cookies, 'POST', body)
        self.assertStatus('200 OK')

        assert recieve_email(self.server_user, 'upload',
                             'user {} uploaded data for the {}'.format(self.server_user, 'Good_Study'))

    def upload_lefse(self):
        self.getPage('/upload/upload_page', self.cookies)
        self.assertStatus('200 OK')
        self.getPage('/upload/upload_metadata?uploadType=lefse&studyName=Test_Lefse&subjectType=human', self.cookies)
        self.assertStatus('200 OK')

        headers, body = self.upload_files(['myMetaData'], [fig.TEST_SUBJECT_ALT], ['text/tab-seperated-values'])
        self.getPage('/upload/validate_metadata?barcodes_type=None', headers + self.cookies, 'POST', body)
        self.assertStatus('200 OK')

        headers, body = self.upload_files(['myMetaData'], [fig.TEST_SPECIMEN_ALT], ['text/tab-seperated-values'])
        self.getPage('/upload/validate_metadata?barcodes_type=other', headers + self.cookies, 'POST', body)
        self.assertStatus('200 OK')
        page_body = self.body
        document, errors = tidy_document(page_body)
        # Assert no errors, warnings are okay
        for warn in errors:
            assert not ('error' in warn or 'Error' in warn)

        self.getPage('/upload/upload_data', self.cookies)
        self.assertStatus('200 OK')

        headers, body = self.upload_files(['lefse_table'], [fig.TEST_LEFSE], ['text/tab-seperated-values'])
        self.getPage('/upload/process_data', headers + self.cookies, 'POST', body)
        self.assertStatus('200 OK')

        # Search arguments for retrieving emails with access codes
        assert recieve_email(self.server_user, 'upload',
                             'user {} uploaded data for the {}'.format(self.server_user, 'Test_Lefse'))

    def upload_dualBarcode_metadata(self):
        self.getPage('/upload/upload_page', self.cookies)
        self.assertStatus('200 OK')
        self.getPage('/upload/upload_metadata?uploadType=qiime&studyName=Test_DualBarcodes&subjectType=human',
                     self.cookies)
        self.assertStatus('200 OK')

        headers, body = self.upload_files(['myMetaData'], [fig.TEST_SUBJECT_SHORT], ['text/tab-seperated-values'])
        self.getPage('/upload/validate_metadata?barcodes_type=None', headers + self.cookies, 'POST', body)
        self.assertStatus('200 OK')

        headers, body = self.upload_files(['myMetaData'], [fig.TEST_SPECIMEN_SHORT_DUAL], ['text/tab-seperated-values'])
        self.getPage('/upload/validate_metadata?barcodes_type=dual', headers + self.cookies, 'POST', body)
        self.assertStatus('200 OK')
        page_body = self.body
        documents, errors = tidy_document(page_body)
        # Assert no errors, warnings are okay
        for warn in errors:
            assert not ('error' in warn or 'Error' in warn)

        self.getPage('/upload/upload_data', self.cookies)
        self.assertStatus('200 OK')
        headers, body = self.upload_files(['for_reads', 'rev_reads',
                                           'for_barcodes', 'rev_barcodes'],
                                          [fig.TEST_READS, fig.TEST_REV_READS,
                                           fig.TEST_BARCODES, fig.TEST_BARCODES],
                                          ['application/gzip', 'application/gzip',
                                           'application/gzip', 'application/gzip'])
        self.getPage('/upload/process_data', headers + self.cookies, 'POST', body)
        self.assertStatus('200 OK')

        assert recieve_email(self.server_user, 'upload',
                             'user {} uploaded data for the {}'.format(self.server_user, 'Test_DualBarcodes'))

    def upload_metadata_fail(self):

        # Check the page for uploading metadata
        self.getPage('/upload/upload_page', self.cookies)
        self.assertStatus('200 OK')
        self.getPage('/upload/upload_metadata?uploadType=qiime&studyName=Test_Server&subjectType=human', self.cookies)
        self.assertStatus('200 OK')

        # Check an invalid metadata filetype
        headers, body = self.upload_files(['myMetaData'], [fig.TEST_CONFIG], ['application/gzip'])
        self.getPage('/upload/validate_metadata?barcodes_type=None', headers + self.cookies, 'POST', body)
        self.assertStatus('200 OK')
        page = server.load_webpage('upload_metadata_file',
                                   user=self.server_user,
                                   upload_selected='w3-blue',
                                   home_selected='',
                                   select_barcodes='',
                                   metadata_type='subject',
                                   error='yaml is not a valid filetype.')
        self.assertBody(page)
        Logger.debug('Checked invalid filetype')

        ##################
        # Subject Errors #
        ##################

        # Check a subject metadata file that errors
        headers, body = self.upload_files(['myMetaData'], [fig.TEST_SUBJECT_ERROR], ['text/tab-seperated-values'])
        self.getPage('/upload/validate_metadata?barcodes_type=None', headers + self.cookies, 'POST', body)
        self.assertStatus('200 OK')
        page_body = self.body
        document, errors = tidy_document(page_body)
        # Assert no errors, warnings are okay
        for warn in errors:
            assert not ('error' in warn or 'Error' in warn)

        Logger.debug('Checked metadata that errors')

        # Check a subject metadata file that produces warnings
        headers, body = self.upload_files(['myMetaData'], [fig.TEST_SUBJECT_WARN], ['text/tab-seperated-values'])
        self.getPage('/upload/validate_metadata?barcodes_type=None', headers + self.cookies, 'POST', body)
        self.assertStatus('200 OK')
        warning = '-1\t17\tCategorical Data Warning: Potential categorical data detected. Value Protocol90' +\
            ' may be in error, only 1 found.'
        page = server.load_webpage('upload_metadata_warning',
                                   user=self.server_user,
                                   warning=[warning],
                                   upload_selected='w3-blue',
                                   home_selected='',
                                   next_page='{retry_upload_page}')

        self.assertBody(page)
        Logger.debug('Checked metadata that warns')

        ###################
        # Specimen Errors #
        ###################

        # Check a subject metadata file that has no issues
        headers, body = self.upload_files(['myMetaData'], [fig.TEST_SUBJECT], ['text/tab-seperated-values'])
        self.getPage('/upload/validate_metadata?barcodes_type=None', headers + self.cookies, 'POST', body)
        self.assertStatus('200 OK')

        # Check a specimen metadata file that errors
        headers, body = self.upload_files(['myMetaData'], [fig.TEST_SPECIMEN_ERROR], ['text/tab-seperated-values'])
        self.getPage('/upload/validate_metadata?barcodes_type=sol', headers + self.cookies, 'POST', body)

        self.assertStatus('200 OK')
        page_body = self.body
        document, errors = tidy_document(page_body)
        # Assert no errors, warnings are okay
        for warn in errors:
            assert not ('error' in warn or 'Error' in warn)

        Logger.debug('Checked metadata that errors')

        #####################
        # Specimen Warnings #
        #####################

        # Check a subject metadata file that produces warnings
        headers, body = self.upload_files(['myMetaData'], [fig.TEST_SPECIMEN], ['text/tab-seperated-values'])
        self.getPage('/upload/validate_metadata?barcodes_type=single', headers + self.cookies, 'POST', body)
        self.assertStatus('200 OK')
        error_message = ('-1\t-1\tStudy Name Error: The study name in the metadata (Good_Study)' +
                         ' does not match the name provided for this upload (Test_Server)')
        page = server.load_webpage('upload_metadata_error',
                                   user=self.server_user,
                                   upload_selected='w3-blue',
                                   error=[error_message],
                                   dual_barcodes='style="display:none"',
                                   home_selected='')
        self.assertBody(page)

    def upload_metadata(self):
        self.getPage('/upload/upload_metadata?uploadType=qiime&studyName=Validate_Study&subjectType=human',
                     self.cookies)

        # Check a subject metadata file that has no issues
        headers, body = self.upload_files(['myMetaData'], [fig.TEST_SUBJECT_SHORT], ['text/tab-seperated-values'])
        self.getPage('/upload/validate_metadata?barcodes_type=None', headers + self.cookies, 'POST', body)
        self.assertStatus('200 OK')

        # Check a subject metadata file that produces warnings
        headers, body = self.upload_files(['myMetaData'], [fig.TEST_SPECIMEN_SHORT_WARN], ['text/tab-seperated-values'])
        self.getPage('/upload/validate_metadata?barcodes_type=single', headers + self.cookies, 'POST', body)
        self.assertStatus('200 OK')

        warning = '-1\t41\tCategorical Data Warning: Potential categorical data detected. Value Protocol90' +\
            ' may be in error, only 1 found.'

        page = server.load_webpage('upload_metadata_warning',
                                   user=self.server_user,
                                   warning=[warning],
                                   upload_selected='w3-blue',
                                   home_selected='',
                                   next_page='{upload_data_page}')
        self.assertBody(page)
        Logger.debug('Checked metadata that warns')

        # Continue with warnings
        self.getPage('/upload/continue_metadata_upload', self.cookies, 'POST')
        self.assertStatus('200 OK')
        page = server.load_webpage('upload_data_files',
                                   user=self.server_user,
                                   upload_selected='w3-blue',
                                   success='Specimen metadata uploaded successfully',
                                   dual_barcodes='style="display:none"',
                                   home_selected='')
        self.assertBody(page)
        Logger.debug('Checked a metadata file with no problems')

    def upload_data(self):
        self.getPage('/upload/upload_data', self.cookies)
        self.assertStatus('200 OK')
        headers, body = self.upload_files(['for_reads', 'rev_reads', 'barcodes', 'reads_type'],
                                          [fig.TEST_READS, '', fig.TEST_BARCODES, 'single_end'],
                                          ['application/gzip', 'application/octet-stream',
                                           'application/gzip', ''])
        self.getPage('/upload/process_data', headers + self.cookies, 'POST', body)
        self.assertStatus('200 OK')

        mail = recieve_email(self.server_user, 'upload',
                             'user {} uploaded data for the Validate_Study'.format(self.server_user))
        self.access_code = mail.split('access code:')[1].splitlines()[1]

    def modify_upload(self):
        headers, body = self.upload_files(['myData'], [fig.TEST_READS], ['application/gzip'])
        self.getPage('/upload/modify_upload?data_type=for_reads&access_code=badcode',
                     headers + self.cookies, 'POST', body)
        self.assertStatus('200 OK')
        err_page = server.load_webpage('home',
                                       user=self.server_user,
                                       home_selected='',
                                       upload_selected='w3-blue',
                                       error=err.MissingUploadError().message)
        self.assertBody(err_page)

        self.getPage('/upload/modify_upload?data_type=for_reads&access_code={}'.format(self.access_code),
                     headers + self.cookies, 'POST', body)
        page = server.load_webpage('home',
                                   user=self.server_user,
                                   upload_selected='w3-blue',
                                   home_selected='',
                                   success='Upload modification successful')
        self.assertStatus('200 OK')
        self.assertBody(page)

    #########
    # Study #
    #########
    def select_study(self):
        # Check the view study page
        self.getPage("/study/select_study", headers=self.cookies)
        self.assertStatus('200 OK')

        # Parse the body of the page
        body = self.body.decode('utf-8')
        # Grab the access code
        code = re.search('access_code=(.+?)">', body)
        # Check that it works to access the view_study page
        self.getPage("/study/view_study?access_code={}".format(code.group(1)), headers=self.cookies)
        self.assertStatus('200 OK')

    ############
    # Analysis #
    ############
    def check_analysis_no_privileges(self):
        self.getPage("/analysis/analysis_page", headers=self.cookies)
        self.assertStatus('200 OK')
        page = server.load_webpage('analysis_select_tool',
                                   analysis_selected='w3-blue',
                                   home_selected='',
                                   title='Select Analysis',
                                   user=self.server_user)
        self.assertBody(page)

    def check_analysis_has_privileges(self):
        self.getPage("/analysis/analysis_page", headers=self.cookies)
        self.assertStatus('200 OK')
        page = server.load_webpage('analysis_select_tool',
                                   title='Select Analysis',
                                   analysis_selected='w3-blue',
                                   home_selected='',
                                   privilege='',
                                   user=self.lab_user)
        self.assertBody(page)

    def run_test_analysis(self):
        self.getPage("/study/select_study", headers=self.cookies)
        # Parse the body of the page
        body = self.body.decode('utf-8')
        # Grab the access code
        code = re.findall('access_code=(.+?)">', body)
        self.analyzed_study_code = code[0].strip('"')

        # Load the test config for animal subjects
        headers, body = self.upload_files(['config'], [fig.TEST_ANIMAL_CONFIG], ['text/tab-seperated-values'])

        # Check that it works to access the view_study page
        self.getPage('/analysis/run_analysis?access_code={}&analysis_method=test'.format(code[0]),
                     headers + self.cookies, 'POST', body)
        self.assertStatus('200 OK')
        page = server.load_webpage('home',
                                   user=self.server_user,
                                   home_selected='',
                                   analysis_selected='w3-blue',
                                   privilege='',
                                   title='Welcome to MMEDS',
                                   success='Analysis started you will recieve an email shortly')
        self.assertBody(page)
        sleep(20)

    def view_analysis(self):
        # Check that it works to access the view_study page
        self.getPage("/study/view_study?access_code={}".format(self.analyzed_study_code), headers=self.cookies)
        self.assertStatus('200 OK')
        body = self.body.decode('utf-8')
        # Grab the access code
        analysis_code = re.findall('option value="(.+?)">', body)
        self.getPage("/analysis/view_analysis?access_code={}".format(analysis_code[0]), headers=self.cookies)
        self.assertStatus('200 OK')

    #############
    # Downloads #
    #############

    def download_page_fail(self):
        self.getPage("/study/view_study?access_code={}".format(self.server_code),
                     headers=self.cookies)
        self.assertStatus('200 OK')
        page = server.load_webpage('home',
                                   error=err.MissingUploadError().message,
                                   title='Welcome to Mmeds',
                                   analysis_selected='',
                                   study_selected='w3-blue',
                                   home_selected='',
                                   privilege='',
                                   user=self.server_user)
        self.assertBody(page)

    def download(self):
        self.getPage("/study/select_study", headers=self.cookies)
        # Parse the body of the page
        body = self.body.decode('utf-8')
        # Grab the access code
        code = re.findall('access_code=(.+?)">', body)
        # Check that it works to access the view_study page
        self.getPage("/study/view_study?access_code={}".format(code[0]), headers=self.cookies)
        self.assertStatus('200 OK')

        address = '/download/download_file?file_name=otu_table'
        self.getPage(address, headers=self.cookies)
        self.assertStatus('200 OK')

    def convert(self):
        headers, body = self.upload_files(['myMetaData'],
                                          [fig.TEST_METADATA_SHORTEST],
                                          ['text/tab-seperated-values'])
        addr = '/upload/convert_metadata?convertTo=mixs&unitCol=&skipRows='
        self.getPage(addr, headers + self.cookies, 'POST', body)
        self.assertStatus('200 OK')

    def lab_download(self):
        # Login
        self.getPage("/auth/logout", headers=self.cookies)
        self.assertStatus('200 OK')
        self.getPage("/auth/login?username={}&password={}".format(self.lab_user, sec.TEST_PASS))
        self.assertStatus('200 OK')
        self.getPage("/download/select_study", headers=self.cookies)
        self.assertStatus('200 OK')
        self.getPage("/download/download_study?study_code={}".format(self.access_code), headers=self.cookies)
        self.assertStatus('200 OK')
        metadata_path = self.body.decode('utf-8').split('\n')[34].split('"')[1]
        self.getPage("/download/download_filepath?file_path={}".format(metadata_path), headers=self.cookies)
        self.assertStatus('200 OK')

    def user_download(self):
        # Login
        self.getPage("/auth/logout", headers=self.cookies)
        self.assertStatus('200 OK')
        self.getPage("/auth/login?username={}&password={}".format(self.server_user, sec.TEST_PASS))
        self.assertStatus('200 OK')
        self.getPage("/download/download_study?study_code={}".format(self.access_code), headers=self.cookies)
        self.assertStatus('200 OK')
        page = self.body.decode('utf-8')
        metadata_path = page.split('\n')[34].split('"')[1]
        self.getPage("/download/download_filepath?file_path={}".format(metadata_path), headers=self.cookies)
        self.assertStatus('200 OK')

    ###############
    # SQL queries #
    ###############

    def execute_invalid_query(self):
        self.getPage('/analysis/query_page', headers=self.cookies)
        self.assertStatus('200 OK')
        self.getPage('/analysis/execute_query?query={}'.format('asdf'), self.cookies, 'POST')
        self.assertStatus('200 OK')

    def execute_protected_query(self):
        self.getPage('/analysis/query_page', headers=self.cookies)
        self.assertStatus('200 OK')
        self.getPage('/analysis/execute_query?query={}'.format('Describe+Subjects'), self.cookies, 'POST')
        self.assertStatus('200 OK')

    def execute_query(self):
        self.getPage('/analysis/query_page', headers=self.cookies)
        self.assertStatus('200 OK')
        self.getPage('/analysis/execute_query?query={}'.format('Select+*+from+Subjects'), self.cookies, 'POST')
        self.assertStatus('200 OK')

    def test_fa_single_id(self):
        self.login(False, False)
        self.generate_aliquot_id()

    def generate_aliquot_id(self):
        self.getPage('/query/query_select', headers=self.cookies)
        self.assertStatus('200 OK')
        # Grab all the access codes on the page
        body = self.body.decode('utf-8')
        code = re.findall('access_code=(.+?)">', body)

        self.getPage('/query/select_specimen?access_code={}'.format(code[-1]), headers=self.cookies)
        self.assertStatus('200 OK')

        # Grab link to the first Specimen
        body = self.body.decode('utf-8')
        code = re.findall('http:\/\/localhost\/myapp(.+?)" class="row-link">', body)
        url_path = Path('/tmp/urls.txt')
        url_path.write_text('\n'.join([cod for cod in code]))

        # Open the weight entry page
        self.getPage(code[0].strip(), headers=self.cookies)
        self.assertStatus('200 OK')

        # Submit the new aliquot id
        url = '/query/generate_aliquot_id?AliquotWeight=0.05&AliquotWeightUnit=Kilogram' +\
            '&StorageInstitution=MountSinai&StorageFreezer=Freezer49'
        self.getPage(url, headers=self.cookies)
        self.assertStatus('200 OK')

    def test_fb_generate_multiple_ids(self):
        self.login(False, False)

    def generate_multiple_ids(self):
        # Grab the access code
        self.getPage('/query/query_select', headers=self.cookies)
        self.assertStatus('200 OK')
        # Grab all the access codes on the page
        body = self.body.decode('utf-8')
        code = re.findall('access_code=(.+?)">', body)

        self.getPage('/upload/upload_page', self.cookies)
        self.assertStatus('200 OK')

        headers, body = self.upload_files(['dataFile'], [fig.TEST_ADD_SAMPLE], ['text/tab-seperated-values'])
        self.getPage(f'/upload/upload_additional_metadata?accessCode={code[-1]}&idType=Sample',
                     headers + self.cookies, 'POST', body)
        self.assertStatus('200 OK')
