# Sampling depth for qiime1 analysis
sampling_depth: 1000
# The metadata columns to include in analysis
# To include all columns set to 'all' (no quotes)
# Otherwise list all the column names separated by commas
# Example:
metadata:
  - SpecimenBodySite
# The levels of taxa summary to include in the final summary of the analysis
taxa_levels:
  - 6
# The minimum abundance a taxon must have in a sample in order to be included in the legend
abundance_threshold: 0.1
# The size of the font in the plot legends
font_size: 15
additional_analysis: none
# Columns to perform sub analysis on. 'all', 'none', or a comma seperated list
# If an additional type of analysis should be run
sub_analysis: none
# SparCC stuff
iterations: 5
permutations: 1
type: spearman
