-- MySQL Script generated by MySQL Workbench
-- Thu 05 Mar 2020 07:24:14 AM EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mmeds_data1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mmeds_data1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mmeds_data1` DEFAULT CHARACTER SET utf8 ;
USE `mmeds_data1` ;

-- -----------------------------------------------------
-- Table `mmeds_data1`.`Lab`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Lab` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Lab` (
  `idLab` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `PrimaryInvestigator` VARCHAR(45) NULL DEFAULT NULL,
  `ContactEmail` VARCHAR(45) NULL DEFAULT NULL,
  `ContactName` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idLab`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Study`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Study` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Study` (
  `idStudy` INT NOT NULL,
  `Lab_idLab` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `StudyName` VARCHAR(45) NULL DEFAULT NULL,
  `StudyType` VARCHAR(45) NULL DEFAULT NULL,
  `RelevantLinks` VARCHAR(180) NULL DEFAULT NULL,
  PRIMARY KEY (`idStudy`),
  INDEX `fk_Study_Lab1_idx` (`Lab_idLab` ASC),
  CONSTRAINT `fk_Study_Lab1`
    FOREIGN KEY (`Lab_idLab`)
    REFERENCES `mmeds_data1`.`Lab` (`idLab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Subjects` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Subjects` (
  `idSubjects` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `HostSubjectId` VARCHAR(256) NULL DEFAULT NULL,
  `Nationality` VARCHAR(45) NULL DEFAULT NULL,
  `Sex` VARCHAR(10) NULL DEFAULT NULL,
  `BirthYear` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idSubjects`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Type` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Type` (
  `idType` INT NOT NULL,
  `SpecimenType` VARCHAR(45) NULL DEFAULT NULL,
  `UberonCodeType` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`CollectionSite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`CollectionSite` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`CollectionSite` (
  `idCollectionSite` INT NOT NULL,
  `Latitude` DECIMAL(18,9) NULL DEFAULT NULL,
  `Longitude` DECIMAL(18,9) NULL DEFAULT NULL,
  `Depth` DECIMAL(18,9) NULL DEFAULT NULL,
  `Elevation` DECIMAL(18,9) NULL DEFAULT NULL,
  `Feature` VARCHAR(45) NULL DEFAULT NULL,
  `Biome` VARCHAR(45) NULL DEFAULT NULL,
  `Material` VARCHAR(45) NULL DEFAULT NULL,
  `CollectionSiteTechnician` VARCHAR(45) NULL DEFAULT NULL,
  `Environment` VARCHAR(45) NULL DEFAULT NULL,
  `CollectionSiteName` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idCollectionSite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`BodySite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`BodySite` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`BodySite` (
  `idBodySite` INT NOT NULL,
  `SpecimenBodySite` VARCHAR(45) NULL DEFAULT NULL,
  `UberonCodeBodySite` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idBodySite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Experiment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Experiment` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Experiment` (
  `idExperiment` INT NOT NULL,
  `Study_idStudy` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `ExperimentName` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idExperiment`),
  INDEX `fk_Experiment_Study1_idx` (`Study_idStudy` ASC),
  CONSTRAINT `fk_Experiment_Study1`
    FOREIGN KEY (`Study_idStudy`)
    REFERENCES `mmeds_data1`.`Study` (`idStudy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Chow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Chow` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Chow` (
  `idChow` INT NOT NULL,
  `Company` VARCHAR(45) NULL DEFAULT NULL COMMENT '(Vendor) Maybe break into its own table',
  `ProductName` VARCHAR(45) NULL DEFAULT NULL,
  `ProductCode` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idChow`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`ChowDates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`ChowDates` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`ChowDates` (
  `idChowDates` INT NOT NULL,
  `user_id` INT NULL,
  `ChowStartDate` DATETIME NULL DEFAULT NULL,
  `ChowEndDate` DATETIME NULL DEFAULT NULL,
  `Chow_idChow` INT NOT NULL,
  PRIMARY KEY (`idChowDates`),
  INDEX `fk_ChowDates_Chow1_idx` (`Chow_idChow` ASC),
  CONSTRAINT `fk_ChowDates_Chow1`
    FOREIGN KEY (`Chow_idChow`)
    REFERENCES `mmeds_data1`.`Chow` (`idChow`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Species`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Species` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Species` (
  `idSpecies` INT NOT NULL,
  `SpeciesName` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idSpecies`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Strain`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Strain` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Strain` (
  `idStrain` INT NOT NULL,
  `StrainName` VARCHAR(45) NULL DEFAULT NULL,
  `StrainProducer` VARCHAR(45) CHARACTER SET 'dec8' NULL DEFAULT NULL COMMENT 'Move this to Vender new table linked to AnimalSubject\nAny information about the animals environment while produced by the vender\nCan have different microbes in different rooms\nTrack information on whether animals are GermFree (GF) or not, initially as part of strain\nthis can change for a particular AnimalSubject\nTreat this like an intervention, For GF there would be a \'Colonization\' intervention\n',
  `StrainID` VARCHAR(45) NULL,
  `Species_idSpecies` INT NOT NULL,
  PRIMARY KEY (`idStrain`),
  INDEX `fk_Strain_Species1_idx` (`Species_idSpecies` ASC),
  CONSTRAINT `fk_Strain_Species1`
    FOREIGN KEY (`Species_idSpecies`)
    REFERENCES `mmeds_data1`.`Species` (`idSpecies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Facility`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Facility` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Facility` (
  `idFacility` INT NOT NULL,
  `FacilityName` VARCHAR(45) NULL DEFAULT NULL,
  `FacilityLocation` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idFacility`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Husbandry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Husbandry` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Husbandry` (
  `idHusbandry` INT NOT NULL COMMENT 'New table for pedigree. Stanford paper, changes in microbiome over multipe generations Justin Soninburg 2017(ish).',
  `user_id` INT NULL,
  `BreedingProgram` VARCHAR(45) NULL DEFAULT NULL,
  `LightDarkCycle` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Move lightDark, Temp, Enrichment, to housing can change over time',
  `Temperature` VARCHAR(45) NULL DEFAULT NULL,
  `EnvironmentalEnrichment` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idHusbandry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Vendor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Vendor` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Vendor` (
  `idVendor` INT NOT NULL,
  `VendorName` VARCHAR(45) NULL DEFAULT NULL,
  `VendorLocation` VARCHAR(45) NULL DEFAULT NULL,
  `VendorStrainInfo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idVendor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`AnimalSubjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`AnimalSubjects` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`AnimalSubjects` (
  `idAnimalSubjects` INT NOT NULL COMMENT 'Merge with the regular subject table',
  `user_id` INT NULL,
  `BirthDate` VARCHAR(45) NULL DEFAULT NULL,
  `ChowDates_idChowDates` INT NOT NULL,
  `Strain_idStrain` INT NOT NULL,
  `Facility_idFacility` INT NOT NULL,
  `Weight` VARCHAR(45) NULL DEFAULT NULL,
  `Sex` VARCHAR(45) NULL DEFAULT NULL,
  `Husbandry_idHusbandry` INT NOT NULL,
  `Vendor_idVendor` INT NOT NULL,
  `AnimalSubjectID` VARCHAR(45) NULL,
  PRIMARY KEY (`idAnimalSubjects`),
  INDEX `fk_AnimalSubjects_ChowDates1_idx` (`ChowDates_idChowDates` ASC),
  INDEX `fk_AnimalSubjects_Strain1_idx` (`Strain_idStrain` ASC),
  INDEX `fk_AnimalSubjects_Facility1_idx` (`Facility_idFacility` ASC),
  INDEX `fk_AnimalSubjects_Husbandry1_idx` (`Husbandry_idHusbandry` ASC),
  INDEX `fk_AnimalSubjects_Vendor1_idx` (`Vendor_idVendor` ASC),
  CONSTRAINT `fk_AnimalSubjects_ChowDates1`
    FOREIGN KEY (`ChowDates_idChowDates`)
    REFERENCES `mmeds_data1`.`ChowDates` (`idChowDates`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AnimalSubjects_Strain1`
    FOREIGN KEY (`Strain_idStrain`)
    REFERENCES `mmeds_data1`.`Strain` (`idStrain`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AnimalSubjects_Facility1`
    FOREIGN KEY (`Facility_idFacility`)
    REFERENCES `mmeds_data1`.`Facility` (`idFacility`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AnimalSubjects_Husbandry1`
    FOREIGN KEY (`Husbandry_idHusbandry`)
    REFERENCES `mmeds_data1`.`Husbandry` (`idHusbandry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AnimalSubjects_Vendor1`
    FOREIGN KEY (`Vendor_idVendor`)
    REFERENCES `mmeds_data1`.`Vendor` (`idVendor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`SubjectType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`SubjectType` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`SubjectType` (
  `idSubjectType` INT NOT NULL,
  `user_id` INT NULL,
  `SubjectType` VARCHAR(45) NULL DEFAULT NULL,
  `AnimalSubjects_idAnimalSubjects` INT NULL,
  `Subjects_idSubjects` INT NULL,
  PRIMARY KEY (`idSubjectType`),
  INDEX `fk_SubjectType_AnimalSubjects1_idx` (`AnimalSubjects_idAnimalSubjects` ASC),
  INDEX `fk_SubjectType_Subjects1_idx` (`Subjects_idSubjects` ASC),
  CONSTRAINT `fk_SubjectType_AnimalSubjects1`
    FOREIGN KEY (`AnimalSubjects_idAnimalSubjects`)
    REFERENCES `mmeds_data1`.`AnimalSubjects` (`idAnimalSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SubjectType_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_data1`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Specimen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Specimen` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Specimen` (
  `idSpecimen` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `Type_idType` INT NOT NULL,
  `BodySite_idBodySite` INT NOT NULL,
  `Experiment_idExperiment` INT NOT NULL,
  `CollectionSite_idCollectionSite` INT NOT NULL,
  `SpecimenID` VARCHAR(256) NULL DEFAULT NULL,
  `SpecimenCollectionDate` DATE NULL DEFAULT NULL,
  `SpecimenNotes` VARCHAR(180) NULL DEFAULT NULL,
  `SpecimenCollectionTime` TIME NULL DEFAULT NULL,
  `SpecimenWeight` DECIMAL(18,9) NULL DEFAULT NULL,
  `SubjectType_idSubjectType` INT NOT NULL,
  PRIMARY KEY (`idSpecimen`),
  INDEX `fk_Sample_Type1_idx` (`Type_idType` ASC),
  INDEX `fk_Specimen_BodySite1_idx` (`BodySite_idBodySite` ASC),
  INDEX `fk_Specimen_Experiment1_idx` (`Experiment_idExperiment` ASC),
  INDEX `fk_Specimen_CollectionSite1_idx` (`CollectionSite_idCollectionSite` ASC),
  INDEX `fk_Specimen_SubjectType1_idx` (`SubjectType_idSubjectType` ASC),
  CONSTRAINT `fk_Type1`
    FOREIGN KEY (`Type_idType`)
    REFERENCES `mmeds_data1`.`Type` (`idType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specimen_BodySite1`
    FOREIGN KEY (`BodySite_idBodySite`)
    REFERENCES `mmeds_data1`.`BodySite` (`idBodySite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specimen_Experiment1`
    FOREIGN KEY (`Experiment_idExperiment`)
    REFERENCES `mmeds_data1`.`Experiment` (`idExperiment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specimen_CollectionSite1`
    FOREIGN KEY (`CollectionSite_idCollectionSite`)
    REFERENCES `mmeds_data1`.`CollectionSite` (`idCollectionSite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specimen_SubjectType1`
    FOREIGN KEY (`SubjectType_idSubjectType`)
    REFERENCES `mmeds_data1`.`SubjectType` (`idSubjectType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Ethnicity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Ethnicity` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Ethnicity` (
  `idEthnicity` INT NOT NULL,
  `Ethnicity` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idEthnicity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Subjects_has_Ethnicity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Subjects_has_Ethnicity` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Subjects_has_Ethnicity` (
  `Subjects_idSubjects` INT NOT NULL,
  `Ethnicity_idEthnicity` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  INDEX `fk_Subjects_has_Ethnicity_Ethnicity1_idx` (`Ethnicity_idEthnicity` ASC),
  INDEX `fk_Subjects_has_Ethnicity_Subjects1_idx` (`Subjects_idSubjects` ASC),
  CONSTRAINT `fk_Subjects_has_Ethnicity_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_data1`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subjects_has_Ethnicity_Ethnicity1`
    FOREIGN KEY (`Ethnicity_idEthnicity`)
    REFERENCES `mmeds_data1`.`Ethnicity` (`idEthnicity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`IllnessBroadCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`IllnessBroadCategory` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`IllnessBroadCategory` (
  `idIllnessBroadCategory` INT NOT NULL,
  `ICDFirstCharacter` VARCHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idIllnessBroadCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`IllnessCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`IllnessCategory` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`IllnessCategory` (
  `idIllnessCategory` INT NOT NULL,
  `IllnessBroadCategory_idIllnessBroadCategory` INT NOT NULL,
  `ICDCategory` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idIllnessCategory`),
  INDEX `fk_IllnessCategory_IllnessBroadCategory1_idx` (`IllnessBroadCategory_idIllnessBroadCategory` ASC),
  CONSTRAINT `fk_IllnessCategory_IllnessBroadCategory1`
    FOREIGN KEY (`IllnessBroadCategory_idIllnessBroadCategory`)
    REFERENCES `mmeds_data1`.`IllnessBroadCategory` (`idIllnessBroadCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`IllnessDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`IllnessDetails` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`IllnessDetails` (
  `idIllnessDetails` INT NOT NULL,
  `IllnessCategory_idIllnessCategory` INT NOT NULL,
  `ICDDetails` VARCHAR(3) NULL DEFAULT NULL,
  `ICDExtension` VARCHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idIllnessDetails`),
  INDEX `fk_IllnessDetails_IllnessCategory1_idx` (`IllnessCategory_idIllnessCategory` ASC),
  CONSTRAINT `fk_IllnessDetails_IllnessCategory1`
    FOREIGN KEY (`IllnessCategory_idIllnessCategory`)
    REFERENCES `mmeds_data1`.`IllnessCategory` (`idIllnessCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Illness`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Illness` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Illness` (
  `idIllness` INT NOT NULL,
  `Subjects_idSubjects` INT NOT NULL,
  `IllnessDetails_idIllnessDetails` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `IllnessStartDate` DATE NULL DEFAULT NULL,
  `IllnessEndDate` DATE NULL DEFAULT NULL,
  `IllnessDescription` VARCHAR(256) NULL DEFAULT NULL,
  `IllnessInstanceID` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`idIllness`),
  INDEX `fk_Illness_Subjects1_idx` (`Subjects_idSubjects` ASC),
  INDEX `fk_Illness_IllnessDetails1_idx` (`IllnessDetails_idIllnessDetails` ASC),
  CONSTRAINT `fk_Illness_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_data1`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Illness_IllnessDetails1`
    FOREIGN KEY (`IllnessDetails_idIllnessDetails`)
    REFERENCES `mmeds_data1`.`IllnessDetails` (`idIllnessDetails`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Interventions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Interventions` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Interventions` (
  `idInterventions` INT NOT NULL,
  `InterventionName` VARCHAR(45) NULL DEFAULT NULL,
  `InterventionType` VARCHAR(45) NULL DEFAULT NULL,
  `InterventionCode` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idInterventions`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Intervention`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Intervention` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Intervention` (
  `idIntervention` INT NOT NULL,
  `Subjects_idSubjects` INT NOT NULL,
  `Interventions_idInterventions` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `InterventionNotes` VARCHAR(180) NULL DEFAULT NULL,
  `InterventionStartDate` DATE NULL DEFAULT NULL,
  `InterventionEndDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idIntervention`),
  INDEX `fk_Treatment_Subjects1_idx` (`Subjects_idSubjects` ASC),
  INDEX `fk_Intervention_Interventions1_idx` (`Interventions_idInterventions` ASC),
  CONSTRAINT `fk_Treatment_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_data1`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Intervention_Interventions1`
    FOREIGN KEY (`Interventions_idInterventions`)
    REFERENCES `mmeds_data1`.`Interventions` (`idInterventions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Aliquot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Aliquot` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Aliquot` (
  `idAliquot` INT NOT NULL,
  `Specimen_idSpecimen` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `AliquotID` VARCHAR(256) NULL DEFAULT NULL,
  `AliquotWeight` DECIMAL(18,9) NULL DEFAULT NULL,
  PRIMARY KEY (`idAliquot`),
  INDEX `fk_Aliquot_Specimen1_idx` (`Specimen_idSpecimen` ASC),
  CONSTRAINT `fk_Aliquot_Specimen1`
    FOREIGN KEY (`Specimen_idSpecimen`)
    REFERENCES `mmeds_data1`.`Specimen` (`idSpecimen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`SampleProtocols`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`SampleProtocols` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`SampleProtocols` (
  `idSampleProtocols` INT NOT NULL,
  `SampleConditions` VARCHAR(256) NULL DEFAULT NULL,
  `SampleTool` VARCHAR(256) NULL DEFAULT NULL,
  `SampleToolVersion` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`idSampleProtocols`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`SampleProtocol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`SampleProtocol` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`SampleProtocol` (
  `idSampleProtocol` INT NOT NULL,
  `SampleProtocols_idSampleProtocols` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `SampleDatePerformed` DATETIME NULL DEFAULT NULL,
  `SampleProcessor` VARCHAR(45) NULL DEFAULT NULL,
  `SampleProtocolInformation` VARCHAR(180) NULL DEFAULT NULL,
  `SampleProtocolID` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`idSampleProtocol`),
  INDEX `fk_SampleProtocol_SampleProtocols1_idx` (`SampleProtocols_idSampleProtocols` ASC),
  CONSTRAINT `fk_SampleProtocol_SampleProtocols1`
    FOREIGN KEY (`SampleProtocols_idSampleProtocols`)
    REFERENCES `mmeds_data1`.`SampleProtocols` (`idSampleProtocols`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Sample`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Sample` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Sample` (
  `idSample` INT NOT NULL,
  `SampleProtocol_idSampleProtocol` INT NOT NULL,
  `Aliquot_idAliquot` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `SampleID` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`idSample`),
  INDEX `fk_Sample_Aliquot1_idx` (`Aliquot_idAliquot` ASC),
  INDEX `fk_Sample_SampleProtocol1_idx` (`SampleProtocol_idSampleProtocol` ASC),
  CONSTRAINT `fk_Sample_Aliquot1`
    FOREIGN KEY (`Aliquot_idAliquot`)
    REFERENCES `mmeds_data1`.`Aliquot` (`idAliquot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sample_SampleProtocol1`
    FOREIGN KEY (`SampleProtocol_idSampleProtocol`)
    REFERENCES `mmeds_data1`.`SampleProtocol` (`idSampleProtocol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`RawDataProtocols`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`RawDataProtocols` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`RawDataProtocols` (
  `idRawDataProtocols` INT NOT NULL,
  `SequencingMethod` VARCHAR(256) NULL DEFAULT NULL,
  `RawDataConditions` VARCHAR(256) NULL DEFAULT NULL,
  `Primer` VARCHAR(256) NULL DEFAULT NULL,
  `TargetGene` VARCHAR(256) NULL DEFAULT NULL,
  `FinishingStrategyStatus` VARCHAR(256) NULL DEFAULT NULL,
  `FinishingStrategyCoverage` VARCHAR(256) NULL DEFAULT NULL,
  `NumberOfContigs` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idRawDataProtocols`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`RawDataProtocol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`RawDataProtocol` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`RawDataProtocol` (
  `idRawDataProtocol` INT NOT NULL,
  `RawDataProtocols_idRawDataProtocols` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `RawDataDatePerformed` DATETIME NULL DEFAULT NULL,
  `RawDataProcessor` VARCHAR(45) NULL DEFAULT NULL,
  `RawDataProtocolID` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`idRawDataProtocol`),
  INDEX `fk_RawDataProtocol_RawDataProtocols1_idx` (`RawDataProtocols_idRawDataProtocols` ASC),
  CONSTRAINT `fk_RawDataProtocol_RawDataProtocols1`
    FOREIGN KEY (`RawDataProtocols_idRawDataProtocols`)
    REFERENCES `mmeds_data1`.`RawDataProtocols` (`idRawDataProtocols`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`RawData`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`RawData` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`RawData` (
  `idRawData` INT NOT NULL,
  `Sample_idSample` INT NOT NULL,
  `RawDataProtocol_idRawDataProtocol` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `RawDataID` VARCHAR(256) NULL DEFAULT NULL,
  `BarcodeSequence` VARCHAR(256) NULL DEFAULT NULL,
  `LinkerPrimerSequence` VARCHAR(256) NULL DEFAULT NULL,
  `RawDataDescription` VARCHAR(256) NULL DEFAULT NULL,
  `RawDataAdditionalInformation` VARCHAR(180) NULL DEFAULT NULL,
  PRIMARY KEY (`idRawData`),
  INDEX `fk_RawData_Sample1_idx` (`Sample_idSample` ASC),
  INDEX `fk_RawData_RawDataProtocol1_idx` (`RawDataProtocol_idRawDataProtocol` ASC),
  CONSTRAINT `fk_RawData_Sample1`
    FOREIGN KEY (`Sample_idSample`)
    REFERENCES `mmeds_data1`.`Sample` (`idSample`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RawData_RawDataProtocol1`
    FOREIGN KEY (`RawDataProtocol_idRawDataProtocol`)
    REFERENCES `mmeds_data1`.`RawDataProtocol` (`idRawDataProtocol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`ResultsProtocols`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`ResultsProtocols` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`ResultsProtocols` (
  `idResultsProtocols` INT NOT NULL,
  `ResultsMethod` VARCHAR(256) NULL DEFAULT NULL,
  `ResultsTool` VARCHAR(256) NULL DEFAULT NULL,
  `ResultsToolVersion` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`idResultsProtocols`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`ResultsProtocol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`ResultsProtocol` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`ResultsProtocol` (
  `idResultsProtocol` INT NOT NULL,
  `ResultsProtocols_idResultsProtocols` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `ResultsDatePerformed` DATETIME NULL DEFAULT NULL,
  `ResultsProcessor` VARCHAR(45) NULL DEFAULT NULL,
  `ResultsProtocolID` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`idResultsProtocol`),
  INDEX `fk_ResultsProtocols_ResultsProtocols1_idx` (`ResultsProtocols_idResultsProtocols` ASC),
  CONSTRAINT `fk_ResultsProtocols_ResultsProtocols1`
    FOREIGN KEY (`ResultsProtocols_idResultsProtocols`)
    REFERENCES `mmeds_data1`.`ResultsProtocols` (`idResultsProtocols`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Results` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Results` (
  `idResults` INT NOT NULL,
  `RawData_Sample_idSample` INT NOT NULL,
  `ResultsProtocol_idResultsProtocol` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `ResultID` VARCHAR(45) NULL DEFAULT NULL,
  `ResultsLocation` VARCHAR(180) NULL DEFAULT NULL,
  PRIMARY KEY (`idResults`),
  INDEX `fk_Results_RawData1_idx` (`RawData_Sample_idSample` ASC),
  INDEX `fk_Results_ResultsProtocols1_idx` (`ResultsProtocol_idResultsProtocol` ASC),
  CONSTRAINT `fk_Results_RawData1`
    FOREIGN KEY (`RawData_Sample_idSample`)
    REFERENCES `mmeds_data1`.`RawData` (`Sample_idSample`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Results_ResultsProtocols1`
    FOREIGN KEY (`ResultsProtocol_idResultsProtocol`)
    REFERENCES `mmeds_data1`.`ResultsProtocol` (`idResultsProtocol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Genotypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Genotypes` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Genotypes` (
  `idGenotypes` INT NOT NULL,
  `Genotype` VARCHAR(180) NULL DEFAULT NULL,
  PRIMARY KEY (`idGenotypes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Subjects_has_Genotypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Subjects_has_Genotypes` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Subjects_has_Genotypes` (
  `Subjects_idSubjects` INT NOT NULL,
  `Genotypes_idGenotypes` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  INDEX `fk_Subjects_has_Genotypes_Genotypes1_idx` (`Genotypes_idGenotypes` ASC),
  INDEX `fk_Subjects_has_Genotypes_Subjects1_idx` (`Subjects_idSubjects` ASC),
  CONSTRAINT `fk_Subjects_has_Genotypes_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_data1`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subjects_has_Genotypes_Genotypes1`
    FOREIGN KEY (`Genotypes_idGenotypes`)
    REFERENCES `mmeds_data1`.`Genotypes` (`idGenotypes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Weights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Weights` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Weights` (
  `idWeights` INT NOT NULL,
  `Subjects_idSubjects` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `WeightDateCollected` DATE NULL DEFAULT NULL,
  `Weight` DECIMAL(18,9) NULL DEFAULT NULL,
  PRIMARY KEY (`idWeights`),
  INDEX `fk_Weights_Subjects1_idx` (`Subjects_idSubjects` ASC),
  CONSTRAINT `fk_Weights_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_data1`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Heights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Heights` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Heights` (
  `idHeights` INT NOT NULL,
  `Subjects_idSubjects` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `HeightDateCollected` DATE NULL DEFAULT NULL,
  `Height` DECIMAL(18,9) NULL DEFAULT NULL,
  PRIMARY KEY (`idHeights`),
  INDEX `fk_Heights_Subjects1_idx` (`Subjects_idSubjects` ASC),
  CONSTRAINT `fk_Heights_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_data1`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Housing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Housing` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Housing` (
  `idHousing` INT NOT NULL,
  `user_id` INT NULL,
  `TankID` VARCHAR(45) NULL,
  `TypeOfFacility` VARCHAR(45) NULL DEFAULT NULL,
  `TypeOfBedding` VARCHAR(45) NULL DEFAULT NULL,
  `TypeOfHousing` VARCHAR(45) NULL DEFAULT NULL,
  `NumberOfCageCompanions` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Maybe change to cage capacity. Add a unique \'cageID\' along with start and end dates for housing',
  `TankShape` VARCHAR(45) NULL DEFAULT NULL,
  `TankMaterial` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idHousing`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`SubjectType_has_Experiment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`SubjectType_has_Experiment` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`SubjectType_has_Experiment` (
  `SubjectType_idSubjectType` INT NOT NULL,
  `Experiment_idExperiment` INT NOT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`SubjectType_idSubjectType`, `Experiment_idExperiment`),
  INDEX `fk_SubjectType_has_Experiment_Experiment1_idx` (`Experiment_idExperiment` ASC),
  INDEX `fk_SubjectType_has_Experiment_SubjectType1_idx` (`SubjectType_idSubjectType` ASC),
  CONSTRAINT `fk_SubjectType_has_Experiment_SubjectType1`
    FOREIGN KEY (`SubjectType_idSubjectType`)
    REFERENCES `mmeds_data1`.`SubjectType` (`idSubjectType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SubjectType_has_Experiment_Experiment1`
    FOREIGN KEY (`Experiment_idExperiment`)
    REFERENCES `mmeds_data1`.`Experiment` (`idExperiment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`HousingDates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`HousingDates` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`HousingDates` (
  `idHousingDates` INT NOT NULL,
  `user_id` INT NULL,
  `HousingStartDate` VARCHAR(45) NULL,
  `HousingEndDate` VARCHAR(45) NULL,
  `Housing_idHousing` INT NOT NULL,
  `AnimalSubjects_idAnimalSubjects` INT NOT NULL,
  PRIMARY KEY (`idHousingDates`),
  INDEX `fk_HousingDates_Housing1_idx` (`Housing_idHousing` ASC),
  INDEX `fk_HousingDates_AnimalSubjects1_idx` (`AnimalSubjects_idAnimalSubjects` ASC),
  CONSTRAINT `fk_HousingDates_Housing1`
    FOREIGN KEY (`Housing_idHousing`)
    REFERENCES `mmeds_data1`.`Housing` (`idHousing`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HousingDates_AnimalSubjects1`
    FOREIGN KEY (`AnimalSubjects_idAnimalSubjects`)
    REFERENCES `mmeds_data1`.`AnimalSubjects` (`idAnimalSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
