-- MySQL Script generated by MySQL Workbench
-- Thu 17 Jan 2019 09:45:14 AM EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mmeds_data1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mmeds_data1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mmeds_data1` DEFAULT CHARACTER SET utf8 ;
USE `mmeds_data1` ;

-- -----------------------------------------------------
-- Table `mmeds_data1`.`Lab`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Lab` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Lab` (
  `idLab` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `PrimaryInvestigator` VARCHAR(45) NULL DEFAULT NULL,
  `ContactEmail` VARCHAR(45) NULL DEFAULT NULL,
  `ContactName` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idLab`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Study`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Study` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Study` (
  `idStudy` INT NOT NULL,
  `Lab_idLab` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `StudyName` VARCHAR(45) NULL DEFAULT NULL,
  `StudyType` VARCHAR(45) NULL,
  `RelevantLinks` VARCHAR(180) NULL,
  PRIMARY KEY (`idStudy`),
  INDEX `fk_Study_Lab1_idx` (`Lab_idLab` ASC),
  CONSTRAINT `fk_Study_Lab1`
    FOREIGN KEY (`Lab_idLab`)
    REFERENCES `mmeds_data1`.`Lab` (`idLab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Subjects` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Subjects` (
  `idSubjects` INT NOT NULL,
  `HostSubjectId` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `Nationality` VARCHAR(45) NULL DEFAULT NULL,
  `Sex` VARCHAR(10) NULL DEFAULT NULL,
  `BirthYear` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idSubjects`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Type` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Type` (
  `idType` INT NOT NULL,
  `SpecimenType` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`CollectionSite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`CollectionSite` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`CollectionSite` (
  `idCollectionSite` INT NOT NULL,
  `Latitude` DECIMAL(18,9) NULL DEFAULT NULL,
  `Longitude` DECIMAL(18,9) NULL DEFAULT NULL,
  `Depth` DECIMAL(18,9) NULL DEFAULT NULL,
  `Elevation` DECIMAL(18,9) NULL DEFAULT NULL,
  `Feature` VARCHAR(45) NULL DEFAULT NULL,
  `Biome` VARCHAR(45) NULL DEFAULT NULL,
  `Material` VARCHAR(45) NULL DEFAULT NULL,
  `CollectionSiteTechnician` VARCHAR(45) NULL,
  `Environment` VARCHAR(45) NULL,
  `CollectionSiteName` VARCHAR(45) NULL,
  PRIMARY KEY (`idCollectionSite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`BodySite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`BodySite` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`BodySite` (
  `idBodySite` INT NOT NULL,
  `SpecimenBodySite` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idBodySite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Experiment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Experiment` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Experiment` (
  `idExperiment` INT NOT NULL,
  `Study_idStudy` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `ExperimentName` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idExperiment`),
  INDEX `fk_Experiment_Study1_idx` (`Study_idStudy` ASC),
  CONSTRAINT `fk_Experiment_Study1`
    FOREIGN KEY (`Study_idStudy`)
    REFERENCES `mmeds_data1`.`Study` (`idStudy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Specimen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Specimen` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Specimen` (
  `idSpecimen` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `Subjects_idSubjects` INT NOT NULL,
  `Type_idType` INT NOT NULL,
  `BodySite_idBodySite` INT NOT NULL,
  `Experiment_idExperiment` INT NOT NULL,
  `CollectionSite_idCollectionSite` INT NOT NULL,
  `SpecimenID` VARCHAR(45) NULL,
  `SpecimenCollectionDate` DATE NULL DEFAULT NULL,
  `SpecimenInformation` VARCHAR(180) NULL DEFAULT NULL,
  `SpecimenCollectionTime` TIME NULL,
  `SpecimenWeight` DECIMAL(18,9) NULL,
  PRIMARY KEY (`idSpecimen`),
  INDEX `fk_Sample_Subjects_idx` (`Subjects_idSubjects` ASC),
  INDEX `fk_Sample_Type1_idx` (`Type_idType` ASC),
  INDEX `fk_Specimen_BodySite1_idx` (`BodySite_idBodySite` ASC),
  INDEX `fk_Specimen_Experiment1_idx` (`Experiment_idExperiment` ASC),
  INDEX `fk_Specimen_CollectionSite1_idx` (`CollectionSite_idCollectionSite` ASC),
  CONSTRAINT `fk_Sample_Subjects`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_data1`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Type1`
    FOREIGN KEY (`Type_idType`)
    REFERENCES `mmeds_data1`.`Type` (`idType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specimen_BodySite1`
    FOREIGN KEY (`BodySite_idBodySite`)
    REFERENCES `mmeds_data1`.`BodySite` (`idBodySite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specimen_Experiment1`
    FOREIGN KEY (`Experiment_idExperiment`)
    REFERENCES `mmeds_data1`.`Experiment` (`idExperiment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specimen_CollectionSite1`
    FOREIGN KEY (`CollectionSite_idCollectionSite`)
    REFERENCES `mmeds_data1`.`CollectionSite` (`idCollectionSite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Ethnicity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Ethnicity` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Ethnicity` (
  `idEthnicity` INT NOT NULL,
  `Ethnicity` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idEthnicity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Subjects_has_Ethnicity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Subjects_has_Ethnicity` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Subjects_has_Ethnicity` (
  `Subjects_idSubjects` INT NOT NULL,
  `Ethnicity_idEthnicity` INT NOT NULL,
  `user_id` INT NULL,
  INDEX `fk_Subjects_has_Ethnicity_Ethnicity1_idx` (`Ethnicity_idEthnicity` ASC),
  INDEX `fk_Subjects_has_Ethnicity_Subjects1_idx` (`Subjects_idSubjects` ASC),
  CONSTRAINT `fk_Subjects_has_Ethnicity_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_data1`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subjects_has_Ethnicity_Ethnicity1`
    FOREIGN KEY (`Ethnicity_idEthnicity`)
    REFERENCES `mmeds_data1`.`Ethnicity` (`idEthnicity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Illnesses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Illnesses` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Illnesses` (
  `idIllnesses` INT NOT NULL,
  `ICDCode` VARCHAR(45) NULL DEFAULT NULL,
  `ICDVersion` VARCHAR(45) NULL,
  PRIMARY KEY (`idIllnesses`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Illness`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Illness` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Illness` (
  `idIllness` INT NOT NULL,
  `Subjects_idSubjects` INT NOT NULL,
  `Illnesses_idIllnesses` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `IllnessStartDate` DATE NULL DEFAULT NULL,
  `IllnessEndDate` DATE NULL DEFAULT NULL,
  `IllnessDescription` VARCHAR(180) NULL,
  PRIMARY KEY (`idIllness`),
  INDEX `fk_Illness_Subjects1_idx` (`Subjects_idSubjects` ASC),
  INDEX `fk_Illness_Illnesses1_idx` (`Illnesses_idIllnesses` ASC),
  CONSTRAINT `fk_Illness_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_data1`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Illness_Illnesses1`
    FOREIGN KEY (`Illnesses_idIllnesses`)
    REFERENCES `mmeds_data1`.`Illnesses` (`idIllnesses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Interventions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Interventions` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Interventions` (
  `idInterventions` INT NOT NULL,
  `InterventionName` VARCHAR(45) NULL DEFAULT NULL,
  `InterventionType` VARCHAR(45) NULL,
  `InterventionCode` VARCHAR(45) NULL,
  PRIMARY KEY (`idInterventions`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Intervention`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Intervention` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Intervention` (
  `idIntervention` INT NOT NULL,
  `Subjects_idSubjects` INT NOT NULL,
  `Interventions_idInterventions` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `InterventionDescription` VARCHAR(180) NULL,
  `InterventionStartDate` DATE NULL DEFAULT NULL,
  `InterventionEndDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idIntervention`),
  INDEX `fk_Treatment_Subjects1_idx` (`Subjects_idSubjects` ASC),
  INDEX `fk_Intervention_Interventions1_idx` (`Interventions_idInterventions` ASC),
  CONSTRAINT `fk_Treatment_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_data1`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Intervention_Interventions1`
    FOREIGN KEY (`Interventions_idInterventions`)
    REFERENCES `mmeds_data1`.`Interventions` (`idInterventions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Aliquot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Aliquot` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Aliquot` (
  `idAliquot` INT NOT NULL,
  `Specimen_idSpecimen` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `AliquotID` VARCHAR(45) NULL DEFAULT NULL,
  `AliquotWeight` DECIMAL(18,9) NULL,
  PRIMARY KEY (`idAliquot`),
  INDEX `fk_Aliquot_Specimen1_idx` (`Specimen_idSpecimen` ASC),
  CONSTRAINT `fk_Aliquot_Specimen1`
    FOREIGN KEY (`Specimen_idSpecimen`)
    REFERENCES `mmeds_data1`.`Specimen` (`idSpecimen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`SampleProtocols`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`SampleProtocols` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`SampleProtocols` (
  `idSampleProtocols` INT NOT NULL,
  `SampleConditions` VARCHAR(45) NULL DEFAULT NULL,
  `SampleTool` VARCHAR(45) NULL,
  `SampleToolVersion` VARCHAR(45) NULL,
  PRIMARY KEY (`idSampleProtocols`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`SampleProtocol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`SampleProtocol` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`SampleProtocol` (
  `idSampleProtocol` INT NOT NULL,
  `SampleProtocols_idSampleProtocols` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `SampleDatePerformed` DATETIME NULL DEFAULT NULL,
  `SampleProcessor` VARCHAR(45) NULL DEFAULT NULL,
  `SampleProtocolInformation` VARCHAR(180) NULL,
  `SampleProtocolID` VARCHAR(45) NULL,
  PRIMARY KEY (`idSampleProtocol`),
  INDEX `fk_SampleProtocol_SampleProtocols1_idx` (`SampleProtocols_idSampleProtocols` ASC),
  CONSTRAINT `fk_SampleProtocol_SampleProtocols1`
    FOREIGN KEY (`SampleProtocols_idSampleProtocols`)
    REFERENCES `mmeds_data1`.`SampleProtocols` (`idSampleProtocols`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Sample`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Sample` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Sample` (
  `idSample` INT NOT NULL,
  `SampleProtocol_idSampleProtocol` INT NOT NULL,
  `Aliquot_idAliquot` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `SampleID` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idSample`),
  INDEX `fk_Sample_Aliquot1_idx` (`Aliquot_idAliquot` ASC),
  INDEX `fk_Sample_SampleProtocol1_idx` (`SampleProtocol_idSampleProtocol` ASC),
  CONSTRAINT `fk_Sample_Aliquot1`
    FOREIGN KEY (`Aliquot_idAliquot`)
    REFERENCES `mmeds_data1`.`Aliquot` (`idAliquot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sample_SampleProtocol1`
    FOREIGN KEY (`SampleProtocol_idSampleProtocol`)
    REFERENCES `mmeds_data1`.`SampleProtocol` (`idSampleProtocol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`RawDataProtocols`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`RawDataProtocols` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`RawDataProtocols` (
  `idRawDataProtocols` INT NOT NULL,
  `SequencingMethod` VARCHAR(45) NULL DEFAULT NULL,
  `RawDataConditions` VARCHAR(45) NULL,
  `Primer` VARCHAR(45) NULL,
  `TargetGene` VARCHAR(45) NULL,
  `FinishingStrategyStatus` VARCHAR(45) NULL,
  `FinishingStrategyCoverage` VARCHAR(45) NULL,
  `NumberOfContigs` INT NULL,
  PRIMARY KEY (`idRawDataProtocols`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`RawDataProtocol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`RawDataProtocol` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`RawDataProtocol` (
  `idRawDataProtocol` INT NOT NULL,
  `RawDataProtocols_idRawDataProtocols` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `RawDataDatePerformed` DATETIME NULL DEFAULT NULL,
  `RawDataProcessor` VARCHAR(45) NULL DEFAULT NULL,
  `RawDataProtocolID` VARCHAR(45) NULL,
  PRIMARY KEY (`idRawDataProtocol`),
  INDEX `fk_RawDataProtocol_RawDataProtocols1_idx` (`RawDataProtocols_idRawDataProtocols` ASC),
  CONSTRAINT `fk_RawDataProtocol_RawDataProtocols1`
    FOREIGN KEY (`RawDataProtocols_idRawDataProtocols`)
    REFERENCES `mmeds_data1`.`RawDataProtocols` (`idRawDataProtocols`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`RawData`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`RawData` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`RawData` (
  `idRawData` INT NOT NULL,
  `Sample_idSample` INT NOT NULL,
  `RawDataProtocol_idRawDataProtocol` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `RawDataID` VARCHAR(45) NULL DEFAULT NULL,
  `BarcodeSequence` VARCHAR(45) NULL,
  `LinkerPrimerSequence` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `RawDataAdditionalInformation` VARCHAR(180) NULL,
  PRIMARY KEY (`idRawData`),
  INDEX `fk_RawData_Sample1_idx` (`Sample_idSample` ASC),
  INDEX `fk_RawData_RawDataProtocol1_idx` (`RawDataProtocol_idRawDataProtocol` ASC),
  CONSTRAINT `fk_RawData_Sample1`
    FOREIGN KEY (`Sample_idSample`)
    REFERENCES `mmeds_data1`.`Sample` (`idSample`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RawData_RawDataProtocol1`
    FOREIGN KEY (`RawDataProtocol_idRawDataProtocol`)
    REFERENCES `mmeds_data1`.`RawDataProtocol` (`idRawDataProtocol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`ResultsProtocols`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`ResultsProtocols` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`ResultsProtocols` (
  `idResultsProtocols` INT NOT NULL,
  `ResultsMethod` VARCHAR(45) NULL DEFAULT NULL,
  `ResultsTool` VARCHAR(45) NULL,
  `ResultsToolVersion` VARCHAR(45) NULL,
  PRIMARY KEY (`idResultsProtocols`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`ResultsProtocol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`ResultsProtocol` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`ResultsProtocol` (
  `idResultsProtocol` INT NOT NULL,
  `ResultsProtocols_idResultsProtocols` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `ResultsDatePerformed` DATETIME NULL DEFAULT NULL,
  `ResultsProcessor` VARCHAR(45) NULL DEFAULT NULL,
  `ResultsProtocolID` VARCHAR(45) NULL,
  PRIMARY KEY (`idResultsProtocol`),
  INDEX `fk_ResultsProtocols_ResultsProtocols1_idx` (`ResultsProtocols_idResultsProtocols` ASC),
  CONSTRAINT `fk_ResultsProtocols_ResultsProtocols1`
    FOREIGN KEY (`ResultsProtocols_idResultsProtocols`)
    REFERENCES `mmeds_data1`.`ResultsProtocols` (`idResultsProtocols`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Results` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Results` (
  `idResults` INT NOT NULL,
  `RawData_Sample_idSample` INT NOT NULL,
  `ResultsProtocol_idResultsProtocol` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `ResultID` VARCHAR(45) NULL DEFAULT NULL,
  `ResultsLocation` VARCHAR(180) NULL,
  PRIMARY KEY (`idResults`),
  INDEX `fk_Results_RawData1_idx` (`RawData_Sample_idSample` ASC),
  INDEX `fk_Results_ResultsProtocols1_idx` (`ResultsProtocol_idResultsProtocol` ASC),
  CONSTRAINT `fk_Results_RawData1`
    FOREIGN KEY (`RawData_Sample_idSample`)
    REFERENCES `mmeds_data1`.`RawData` (`Sample_idSample`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Results_ResultsProtocols1`
    FOREIGN KEY (`ResultsProtocol_idResultsProtocol`)
    REFERENCES `mmeds_data1`.`ResultsProtocol` (`idResultsProtocol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Genotypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Genotypes` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Genotypes` (
  `idGenotypes` INT NOT NULL,
  `Genotype` VARCHAR(180) NULL DEFAULT NULL,
  PRIMARY KEY (`idGenotypes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Subjects_has_Genotypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Subjects_has_Genotypes` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Subjects_has_Genotypes` (
  `Subjects_idSubjects` INT NOT NULL,
  `Genotypes_idGenotypes` INT NOT NULL,
  `user_id` INT NULL,
  INDEX `fk_Subjects_has_Genotypes_Genotypes1_idx` (`Genotypes_idGenotypes` ASC),
  INDEX `fk_Subjects_has_Genotypes_Subjects1_idx` (`Subjects_idSubjects` ASC),
  CONSTRAINT `fk_Subjects_has_Genotypes_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_data1`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subjects_has_Genotypes_Genotypes1`
    FOREIGN KEY (`Genotypes_idGenotypes`)
    REFERENCES `mmeds_data1`.`Genotypes` (`idGenotypes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Subjects_has_Experiment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Subjects_has_Experiment` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Subjects_has_Experiment` (
  `Subjects_idSubjects` INT NOT NULL,
  `Experiment_idExperiment` INT NOT NULL,
  `user_id` INT NULL,
  INDEX `fk_Subjects_has_Experiment_Experiment1_idx` (`Experiment_idExperiment` ASC),
  INDEX `fk_Subjects_has_Experiment_Subjects1_idx` (`Subjects_idSubjects` ASC),
  CONSTRAINT `fk_Subjects_has_Experiment_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_data1`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subjects_has_Experiment_Experiment1`
    FOREIGN KEY (`Experiment_idExperiment`)
    REFERENCES `mmeds_data1`.`Experiment` (`idExperiment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Weights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Weights` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Weights` (
  `idWeights` INT NOT NULL,
  `Subjects_idSubjects` INT NOT NULL,
  `user_id` INT NULL,
  `WeightDateCollected` DATE NULL,
  `Weight` DECIMAL(18,9) NULL,
  PRIMARY KEY (`idWeights`),
  INDEX `fk_Weights_Subjects1_idx` (`Subjects_idSubjects` ASC),
  CONSTRAINT `fk_Weights_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_data1`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Heights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Heights` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Heights` (
  `idHeights` INT NOT NULL,
  `Subjects_idSubjects` INT NOT NULL,
  `user_id` INT NULL,
  `HeightDateCollected` DATE NULL,
  `Height` DECIMAL(18,9) NULL,
  PRIMARY KEY (`idHeights`),
  INDEX `fk_Heights_Subjects1_idx` (`Subjects_idSubjects` ASC),
  CONSTRAINT `fk_Heights_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_data1`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
