-- MySQL Script generated by MySQL Workbench
-- Mon 03 Dec 2018 10:55:36 AM EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mmeds_data1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mmeds_data1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mmeds_data1` DEFAULT CHARACTER SET utf8 ;
USE `mmeds_data1` ;

-- -----------------------------------------------------
-- Table `mmeds_data1`.`Lab`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Lab` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Lab` (
  `idLab` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `PrimaryInvestigator` VARCHAR(45) NULL DEFAULT NULL,
  `ContactEmail` VARCHAR(45) NULL DEFAULT NULL,
  `ContactName` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idLab`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Study`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Study` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Study` (
  `idStudy` INT NOT NULL,
  `Lab_idLab` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `StudyName` VARCHAR(45) NULL DEFAULT NULL,
  `StudyType` VARCHAR(45) NULL,
  `RelevantLinks` VARCHAR(180) NULL,
  PRIMARY KEY (`idStudy`, `Lab_idLab`),
  INDEX `fk_Study_Lab1_idx` (`Lab_idLab` ASC),
  CONSTRAINT `fk_Study_Lab1`
    FOREIGN KEY (`Lab_idLab`)
    REFERENCES `mmeds_data1`.`Lab` (`idLab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Subjects` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Subjects` (
  `idSubjects` INT NOT NULL,
  `HostSubjectId` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `Nationality` VARCHAR(45) NULL DEFAULT NULL,
  `Sex` VARCHAR(10) NULL DEFAULT NULL,
  `BirthYear` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idSubjects`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Type` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Type` (
  `idType` INT NOT NULL,
  `SpecimenType` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`CollectionSite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`CollectionSite` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`CollectionSite` (
  `idCollectionSite` INT NOT NULL,
  `Latitude` DECIMAL(18,9) NULL DEFAULT NULL,
  `Longitude` DECIMAL(18,9) NULL DEFAULT NULL,
  `Depth` DECIMAL(18,9) NULL DEFAULT NULL,
  `Elevation` DECIMAL(18,9) NULL DEFAULT NULL,
  `Feature` VARCHAR(45) NULL DEFAULT NULL,
  `Biome` VARCHAR(45) NULL DEFAULT NULL,
  `Material` VARCHAR(45) NULL DEFAULT NULL,
  `CollectionSiteTechnician` VARCHAR(45) NULL,
  `Environment` VARCHAR(45) NULL,
  `CollectionSiteName` VARCHAR(45) NULL,
  PRIMARY KEY (`idCollectionSite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`BodySite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`BodySite` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`BodySite` (
  `idBodySite` INT NOT NULL,
  `SpecimenBodySite` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idBodySite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Experiment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Experiment` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Experiment` (
  `idExperiment` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `ExperimentName` VARCHAR(45) NULL DEFAULT NULL,
  `Study_idStudy` INT NOT NULL,
  `Study_Lab_idLab` INT NOT NULL,
  PRIMARY KEY (`idExperiment`, `Study_idStudy`, `Study_Lab_idLab`),
  INDEX `fk_Experiment_Study1_idx` (`Study_idStudy` ASC, `Study_Lab_idLab` ASC),
  CONSTRAINT `fk_Experiment_Study1`
    FOREIGN KEY (`Study_idStudy` , `Study_Lab_idLab`)
    REFERENCES `mmeds_data1`.`Study` (`idStudy` , `Lab_idLab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Specimen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Specimen` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Specimen` (
  `idSpecimen` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `Subjects_idSubjects` INT NOT NULL,
  `Type_idType` INT NOT NULL,
  `BodySite_idBodySite` INT NOT NULL,
  `Experiment_Study_idStudy` INT NOT NULL,
  `Experiment_idExperiment` INT NOT NULL,
  `Experiment_Study_Lab_idLab` INT NOT NULL,
  `CollectionSite_idCollectionSite` INT NOT NULL,
  `SpecimenID` VARCHAR(45) NULL,
  `SpecimenCollectionDate` DATE NULL DEFAULT NULL,
  `SpecimenInformation` VARCHAR(180) NULL DEFAULT NULL,
  `SpecimenCollectionTime` TIME NULL,
  `SpecimenWeight` DECIMAL(18,9) NULL,
  PRIMARY KEY (`idSpecimen`, `Subjects_idSubjects`, `Type_idType`, `BodySite_idBodySite`, `Experiment_Study_idStudy`, `Experiment_idExperiment`, `Experiment_Study_Lab_idLab`, `CollectionSite_idCollectionSite`),
  INDEX `fk_Sample_Subjects_idx` (`Subjects_idSubjects` ASC),
  INDEX `fk_Sample_Type1_idx` (`Type_idType` ASC),
  INDEX `fk_Specimen_BodySite1_idx` (`BodySite_idBodySite` ASC),
  INDEX `fk_Specimen_Experiment1_idx` (`Experiment_idExperiment` ASC, `Experiment_Study_idStudy` ASC, `Experiment_Study_Lab_idLab` ASC),
  INDEX `fk_Specimen_CollectionSite1_idx` (`CollectionSite_idCollectionSite` ASC),
  CONSTRAINT `fk_Sample_Subjects`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_data1`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Type1`
    FOREIGN KEY (`Type_idType`)
    REFERENCES `mmeds_data1`.`Type` (`idType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specimen_BodySite1`
    FOREIGN KEY (`BodySite_idBodySite`)
    REFERENCES `mmeds_data1`.`BodySite` (`idBodySite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specimen_Experiment1`
    FOREIGN KEY (`Experiment_idExperiment` , `Experiment_Study_idStudy` , `Experiment_Study_Lab_idLab`)
    REFERENCES `mmeds_data1`.`Experiment` (`idExperiment` , `Study_idStudy` , `Study_Lab_idLab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specimen_CollectionSite1`
    FOREIGN KEY (`CollectionSite_idCollectionSite`)
    REFERENCES `mmeds_data1`.`CollectionSite` (`idCollectionSite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Ethnicity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Ethnicity` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Ethnicity` (
  `idEthnicity` INT NOT NULL,
  `Ethnicity` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idEthnicity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Subjects_has_Ethnicity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Subjects_has_Ethnicity` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Subjects_has_Ethnicity` (
  `Subjects_idSubjects` INT NOT NULL,
  `Ethnicity_idEthnicity` INT NOT NULL,
  PRIMARY KEY (`Subjects_idSubjects`, `Ethnicity_idEthnicity`),
  INDEX `fk_Subjects_has_Ethnicity_Ethnicity1_idx` (`Ethnicity_idEthnicity` ASC),
  INDEX `fk_Subjects_has_Ethnicity_Subjects1_idx` (`Subjects_idSubjects` ASC),
  CONSTRAINT `fk_Subjects_has_Ethnicity_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_data1`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subjects_has_Ethnicity_Ethnicity1`
    FOREIGN KEY (`Ethnicity_idEthnicity`)
    REFERENCES `mmeds_data1`.`Ethnicity` (`idEthnicity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Illnesses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Illnesses` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Illnesses` (
  `idIllnesses` INT NOT NULL,
  `ICDCode` VARCHAR(45) NULL DEFAULT NULL,
  `ICDVersion` VARCHAR(45) NULL,
  PRIMARY KEY (`idIllnesses`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Illness`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Illness` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Illness` (
  `idIllness` INT NOT NULL,
  `Subjects_idSubjects` INT NOT NULL,
  `Illnesses_idIllnesses` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `IllnessStartDate` DATE NULL DEFAULT NULL,
  `IllnessEndDate` DATE NULL DEFAULT NULL,
  `IllnessDescription` VARCHAR(180) NULL,
  PRIMARY KEY (`idIllness`, `Subjects_idSubjects`, `Illnesses_idIllnesses`),
  INDEX `fk_Illness_Subjects1_idx` (`Subjects_idSubjects` ASC),
  INDEX `fk_Illness_Illnesses1_idx` (`Illnesses_idIllnesses` ASC),
  CONSTRAINT `fk_Illness_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_data1`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Illness_Illnesses1`
    FOREIGN KEY (`Illnesses_idIllnesses`)
    REFERENCES `mmeds_data1`.`Illnesses` (`idIllnesses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Interventions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Interventions` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Interventions` (
  `idInterventions` INT NOT NULL,
  `InterventionName` VARCHAR(45) NULL DEFAULT NULL,
  `InterventionType` VARCHAR(45) NULL,
  `InterventionCode` VARCHAR(45) NULL,
  PRIMARY KEY (`idInterventions`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Intervention`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Intervention` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Intervention` (
  `idIntervention` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `InterventionDescription` VARCHAR(180) NULL,
  `InterventionStartDate` DATE NULL DEFAULT NULL,
  `InterventionEndDate` DATE NULL DEFAULT NULL,
  `Subjects_idSubjects` INT NOT NULL,
  `Interventions_idInterventions` INT NOT NULL,
  PRIMARY KEY (`idIntervention`, `Subjects_idSubjects`, `Interventions_idInterventions`),
  INDEX `fk_Treatment_Subjects1_idx` (`Subjects_idSubjects` ASC),
  INDEX `fk_Intervention_Interventions1_idx` (`Interventions_idInterventions` ASC),
  CONSTRAINT `fk_Treatment_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_data1`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Intervention_Interventions1`
    FOREIGN KEY (`Interventions_idInterventions`)
    REFERENCES `mmeds_data1`.`Interventions` (`idInterventions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Aliquot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Aliquot` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Aliquot` (
  `idAliquot` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `AliquotID` VARCHAR(45) NULL DEFAULT NULL,
  `AliquotWeight` DECIMAL(18,9) NULL,
  `Specimen_idSpecimen` INT NOT NULL,
  `Specimen_Subjects_idSubjects` INT NOT NULL,
  `Specimen_Type_idType` INT NOT NULL,
  `Specimen_BodySite_idBodySite` INT NOT NULL,
  `Specimen_Experiment_Study_idStudy` INT NOT NULL,
  `Specimen_Experiment_idExperiment` INT NOT NULL,
  `Specimen_Experiment_Study_Lab_idLab` INT NOT NULL,
  `Specimen_CollectionSite_idCollectionSite` INT NOT NULL,
  PRIMARY KEY (`idAliquot`, `Specimen_idSpecimen`, `Specimen_Subjects_idSubjects`, `Specimen_Type_idType`, `Specimen_BodySite_idBodySite`, `Specimen_Experiment_Study_idStudy`, `Specimen_Experiment_idExperiment`, `Specimen_Experiment_Study_Lab_idLab`, `Specimen_CollectionSite_idCollectionSite`),
  INDEX `fk_Aliquot_Specimen1_idx` (`Specimen_idSpecimen` ASC, `Specimen_Subjects_idSubjects` ASC, `Specimen_Type_idType` ASC, `Specimen_BodySite_idBodySite` ASC, `Specimen_Experiment_Study_idStudy` ASC, `Specimen_Experiment_idExperiment` ASC, `Specimen_Experiment_Study_Lab_idLab` ASC, `Specimen_CollectionSite_idCollectionSite` ASC),
  CONSTRAINT `fk_Aliquot_Specimen1`
    FOREIGN KEY (`Specimen_idSpecimen` , `Specimen_Subjects_idSubjects` , `Specimen_Type_idType` , `Specimen_BodySite_idBodySite` , `Specimen_Experiment_Study_idStudy` , `Specimen_Experiment_idExperiment` , `Specimen_Experiment_Study_Lab_idLab` , `Specimen_CollectionSite_idCollectionSite`)
    REFERENCES `mmeds_data1`.`Specimen` (`idSpecimen` , `Subjects_idSubjects` , `Type_idType` , `BodySite_idBodySite` , `Experiment_Study_idStudy` , `Experiment_idExperiment` , `Experiment_Study_Lab_idLab` , `CollectionSite_idCollectionSite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`SampleProtocols`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`SampleProtocols` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`SampleProtocols` (
  `idSampleProtocols` INT NOT NULL,
  `SampleConditions` VARCHAR(45) NULL DEFAULT NULL,
  `SampleTool` VARCHAR(45) NULL,
  `SampleToolVersion` VARCHAR(45) NULL,
  PRIMARY KEY (`idSampleProtocols`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`SampleProtocol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`SampleProtocol` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`SampleProtocol` (
  `idSampleProtocol` INT NOT NULL,
  `SampleProtocols_idSampleProtocols` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `SampleDatePerformed` DATETIME NULL DEFAULT NULL,
  `SampleProcessor` VARCHAR(45) NULL DEFAULT NULL,
  `SampleProtocolInformation` VARCHAR(180) NULL,
  PRIMARY KEY (`idSampleProtocol`, `SampleProtocols_idSampleProtocols`),
  INDEX `fk_SampleProtocol_SampleProtocols1_idx` (`SampleProtocols_idSampleProtocols` ASC),
  CONSTRAINT `fk_SampleProtocol_SampleProtocols1`
    FOREIGN KEY (`SampleProtocols_idSampleProtocols`)
    REFERENCES `mmeds_data1`.`SampleProtocols` (`idSampleProtocols`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Sample`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Sample` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Sample` (
  `idSample` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `SampleProtocol_idSampleProtocol` INT NOT NULL,
  `SampleProtocol_SampleProtocols_idSampleProtocols` INT NOT NULL,
  `SampleID` VARCHAR(45) NULL DEFAULT NULL,
  `Aliquot_idAliquot` INT NOT NULL,
  `Aliquot_Specimen_idSpecimen` INT NOT NULL,
  `Aliquot_Specimen_Subjects_idSubjects` INT NOT NULL,
  `Aliquot_Specimen_Type_idType` INT NOT NULL,
  `Aliquot_Specimen_BodySite_idBodySite` INT NOT NULL,
  `Aliquot_Specimen_Experiment_Study_idStudy` INT NOT NULL,
  `Aliquot_Specimen_Experiment_idExperiment` INT NOT NULL,
  `Aliquot_Specimen_Experiment_Study_Lab_idLab` INT NOT NULL,
  `Aliquot_Specimen_CollectionSite_idCollectionSite` INT NOT NULL,
  PRIMARY KEY (`idSample`, `SampleProtocol_idSampleProtocol`, `SampleProtocol_SampleProtocols_idSampleProtocols`, `Aliquot_idAliquot`, `Aliquot_Specimen_idSpecimen`, `Aliquot_Specimen_Subjects_idSubjects`, `Aliquot_Specimen_Type_idType`, `Aliquot_Specimen_BodySite_idBodySite`, `Aliquot_Specimen_Experiment_Study_idStudy`, `Aliquot_Specimen_Experiment_idExperiment`, `Aliquot_Specimen_Experiment_Study_Lab_idLab`, `Aliquot_Specimen_CollectionSite_idCollectionSite`),
  INDEX `fk_Sample_SampleProtocol1_idx` (`SampleProtocol_idSampleProtocol` ASC, `SampleProtocol_SampleProtocols_idSampleProtocols` ASC),
  INDEX `fk_Sample_Aliquot1_idx` (`Aliquot_idAliquot` ASC, `Aliquot_Specimen_idSpecimen` ASC, `Aliquot_Specimen_Subjects_idSubjects` ASC, `Aliquot_Specimen_Type_idType` ASC, `Aliquot_Specimen_BodySite_idBodySite` ASC, `Aliquot_Specimen_Experiment_Study_idStudy` ASC, `Aliquot_Specimen_Experiment_idExperiment` ASC, `Aliquot_Specimen_Experiment_Study_Lab_idLab` ASC, `Aliquot_Specimen_CollectionSite_idCollectionSite` ASC),
  CONSTRAINT `fk_Sample_SampleProtocol1`
    FOREIGN KEY (`SampleProtocol_idSampleProtocol` , `SampleProtocol_SampleProtocols_idSampleProtocols`)
    REFERENCES `mmeds_data1`.`SampleProtocol` (`idSampleProtocol` , `SampleProtocols_idSampleProtocols`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sample_Aliquot1`
    FOREIGN KEY (`Aliquot_idAliquot` , `Aliquot_Specimen_idSpecimen` , `Aliquot_Specimen_Subjects_idSubjects` , `Aliquot_Specimen_Type_idType` , `Aliquot_Specimen_BodySite_idBodySite` , `Aliquot_Specimen_Experiment_Study_idStudy` , `Aliquot_Specimen_Experiment_idExperiment` , `Aliquot_Specimen_Experiment_Study_Lab_idLab` , `Aliquot_Specimen_CollectionSite_idCollectionSite`)
    REFERENCES `mmeds_data1`.`Aliquot` (`idAliquot` , `Specimen_idSpecimen` , `Specimen_Subjects_idSubjects` , `Specimen_Type_idType` , `Specimen_BodySite_idBodySite` , `Specimen_Experiment_Study_idStudy` , `Specimen_Experiment_idExperiment` , `Specimen_Experiment_Study_Lab_idLab` , `Specimen_CollectionSite_idCollectionSite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`RawDataProtocols`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`RawDataProtocols` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`RawDataProtocols` (
  `idRawDataProtocols` INT NOT NULL,
  `SequencingMethod` VARCHAR(45) NULL DEFAULT NULL,
  `RawDataConditions` VARCHAR(45) NULL,
  `Primer` VARCHAR(45) NULL,
  `TargetGene` VARCHAR(45) NULL,
  `FinishingStrategyStatus` VARCHAR(45) NULL,
  `FinishingStrategyCoverage` VARCHAR(45) NULL,
  `NumberOfContigs` INT NULL,
  PRIMARY KEY (`idRawDataProtocols`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`RawDataProtocol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`RawDataProtocol` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`RawDataProtocol` (
  `idRawDataProtocol` INT NOT NULL,
  `RawDataProtocols_idRawDataProtocols` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `RawDataDatePerformed` DATETIME NULL DEFAULT NULL,
  `RawDataProcessor` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idRawDataProtocol`, `RawDataProtocols_idRawDataProtocols`),
  INDEX `fk_RawDataProtocol_RawDataProtocols1_idx` (`RawDataProtocols_idRawDataProtocols` ASC),
  CONSTRAINT `fk_RawDataProtocol_RawDataProtocols1`
    FOREIGN KEY (`RawDataProtocols_idRawDataProtocols`)
    REFERENCES `mmeds_data1`.`RawDataProtocols` (`idRawDataProtocols`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`RawData`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`RawData` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`RawData` (
  `idRawData` INT NOT NULL,
  `Sample_idSample` INT NOT NULL,
  `RawDataProtocol_idRawDataProtocol` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `RawDataID` VARCHAR(45) NULL DEFAULT NULL,
  `BarcodeSequence` VARCHAR(45) NULL,
  `LinkerPrimerSequence` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `RawDataAdditionalInformation` VARCHAR(180) NULL,
  PRIMARY KEY (`idRawData`, `Sample_idSample`, `RawDataProtocol_idRawDataProtocol`),
  INDEX `fk_RawData_Sample1_idx` (`Sample_idSample` ASC),
  INDEX `fk_RawData_RawDataProtocol1_idx` (`RawDataProtocol_idRawDataProtocol` ASC),
  CONSTRAINT `fk_RawData_Sample1`
    FOREIGN KEY (`Sample_idSample`)
    REFERENCES `mmeds_data1`.`Sample` (`idSample`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RawData_RawDataProtocol1`
    FOREIGN KEY (`RawDataProtocol_idRawDataProtocol`)
    REFERENCES `mmeds_data1`.`RawDataProtocol` (`idRawDataProtocol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`ResultsProtocols`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`ResultsProtocols` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`ResultsProtocols` (
  `idResultsProtocols` INT NOT NULL,
  `ResultsMethod` VARCHAR(45) NULL DEFAULT NULL,
  `ResultsTool` VARCHAR(45) NULL,
  `ResultsToolVersion` VARCHAR(45) NULL,
  PRIMARY KEY (`idResultsProtocols`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`ResultsProtocol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`ResultsProtocol` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`ResultsProtocol` (
  `idResultsProtocol` INT NOT NULL,
  `ResultsProtocols_idResultsProtocols` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `ResultsDatePerformed` DATETIME NULL DEFAULT NULL,
  `ResultsProcessor` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idResultsProtocol`, `ResultsProtocols_idResultsProtocols`),
  INDEX `fk_ResultsProtocols_ResultsProtocols1_idx` (`ResultsProtocols_idResultsProtocols` ASC),
  CONSTRAINT `fk_ResultsProtocols_ResultsProtocols1`
    FOREIGN KEY (`ResultsProtocols_idResultsProtocols`)
    REFERENCES `mmeds_data1`.`ResultsProtocols` (`idResultsProtocols`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Results` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Results` (
  `idResults` INT NOT NULL,
  `RawData_Sample_idSample` INT NOT NULL,
  `ResultsProtocol_idResultsProtocol` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `ResultID` VARCHAR(45) NULL DEFAULT NULL,
  `ResultsLocation` VARCHAR(180) NULL,
  PRIMARY KEY (`idResults`, `RawData_Sample_idSample`, `ResultsProtocol_idResultsProtocol`),
  INDEX `fk_Results_RawData1_idx` (`RawData_Sample_idSample` ASC),
  INDEX `fk_Results_ResultsProtocols1_idx` (`ResultsProtocol_idResultsProtocol` ASC),
  CONSTRAINT `fk_Results_RawData1`
    FOREIGN KEY (`RawData_Sample_idSample`)
    REFERENCES `mmeds_data1`.`RawData` (`Sample_idSample`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Results_ResultsProtocols1`
    FOREIGN KEY (`ResultsProtocol_idResultsProtocol`)
    REFERENCES `mmeds_data1`.`ResultsProtocol` (`idResultsProtocol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Genotypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Genotypes` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Genotypes` (
  `idGenotypes` INT NOT NULL,
  `Genotype` VARCHAR(180) NULL DEFAULT NULL,
  PRIMARY KEY (`idGenotypes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Subjects_has_Genotypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Subjects_has_Genotypes` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Subjects_has_Genotypes` (
  `Subjects_idSubjects` INT NOT NULL,
  `Genotypes_idGenotypes` INT NOT NULL,
  PRIMARY KEY (`Subjects_idSubjects`, `Genotypes_idGenotypes`),
  INDEX `fk_Subjects_has_Genotypes_Genotypes1_idx` (`Genotypes_idGenotypes` ASC),
  INDEX `fk_Subjects_has_Genotypes_Subjects1_idx` (`Subjects_idSubjects` ASC),
  CONSTRAINT `fk_Subjects_has_Genotypes_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_data1`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subjects_has_Genotypes_Genotypes1`
    FOREIGN KEY (`Genotypes_idGenotypes`)
    REFERENCES `mmeds_data1`.`Genotypes` (`idGenotypes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Subjects_has_Experiment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Subjects_has_Experiment` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Subjects_has_Experiment` (
  `Subjects_idSubjects` INT NOT NULL,
  `Experiment_idExperiment` INT NOT NULL,
  PRIMARY KEY (`Subjects_idSubjects`, `Experiment_idExperiment`),
  INDEX `fk_Subjects_has_Experiment_Experiment1_idx` (`Experiment_idExperiment` ASC),
  INDEX `fk_Subjects_has_Experiment_Subjects1_idx` (`Subjects_idSubjects` ASC),
  CONSTRAINT `fk_Subjects_has_Experiment_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_data1`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subjects_has_Experiment_Experiment1`
    FOREIGN KEY (`Experiment_idExperiment`)
    REFERENCES `mmeds_data1`.`Experiment` (`idExperiment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Weights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Weights` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Weights` (
  `idWeights` INT NOT NULL,
  `Subjects_idSubjects` INT NOT NULL,
  `user_id` INT NULL,
  `WeightDateCollected` DATE NULL,
  `Weight` DECIMAL(18,9) NULL,
  PRIMARY KEY (`idWeights`, `Subjects_idSubjects`),
  INDEX `fk_Weights_Subjects1_idx` (`Subjects_idSubjects` ASC),
  CONSTRAINT `fk_Weights_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_data1`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmeds_data1`.`Heights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmeds_data1`.`Heights` ;

CREATE TABLE IF NOT EXISTS `mmeds_data1`.`Heights` (
  `idHeights` INT NOT NULL,
  `Subjects_idSubjects` INT NOT NULL,
  `user_id` INT NULL,
  `HeightDateCollected` DATE NULL,
  `Height` DECIMAL(18,9) NULL,
  PRIMARY KEY (`idHeights`, `Subjects_idSubjects`),
  INDEX `fk_Heights_Subjects1_idx` (`Subjects_idSubjects` ASC),
  CONSTRAINT `fk_Heights_Subjects1`
    FOREIGN KEY (`Subjects_idSubjects`)
    REFERENCES `mmeds_data1`.`Subjects` (`idSubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
