name: MMEDs Tests

on: [push
]

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install packages
        run: sudo apt-get install tidy environment-modules -y; pip install cryptography;
      - name: Start Services
        run: sudo systemctl start mysql.service; sudo systemctl start mongod.service;
      - name: Mysql Setup
        run: mysql -u root -proot < setup.sql
      - name: Server data setup
        run: mkdir ~/mmeds_server_data; mkdir ~/conda_envs; mkdir -p ~/conda_env_files/pheniqs; mkdir -p ~/.modules/modulefiles; cp -r ./test_files ~/mmeds_server_data/.; cp ./mmeds/resources/mmeds_stats.yaml ~/mmeds_server_data/.; cp -r ./modules/* ~/.modules/modulefiles/.; cp -r ./conda_env_files/* ~/conda_env_files/.;

      - name: Python install
        run: sudo python setup.py install; pip install git+https://github.com/clemente-lab/mmeds-meta;

      - name: install jupyter
        run: conda env create -f ./conda_env_files/jupyter_env.yaml -p ~/conda_envs/jupyter

      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: ../../../conda_env_files/jupyter_env.yaml
          activate-environment: jupyter
          auto-activate-base: false
      - name: jupyter create kernel
        run: 'python -m ipykernel install --name jupyter --display-name "Jupyter" --user'

      - name: install qiime
        run: conda env create -f ./conda_env_files/qiime2-2020.8_env.yaml -p ~/conda_envs/qiime2-2020.8

      - name: install R
        run: sudo apt install dirmngr gnupg apt-transport-https ca-certificates software-properties-common; sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9; sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/'; sudo apt install r-base;

      - name: install R dependencies
        run: sudo Rscript -e 'install.packages("GGally",dependencies=TRUE)'; sudo Rscript -e 'install.packages("ggrepel",dependencies=TRUE)'; sudo Rscript -e 'install.packages("RColorBrewer",dependencies=TRUE)'; sudo Rscript -e 'install.packages("ggplot2",dependencies=TRUE)';

      - name: install pheniqs
        run: conda env create -f ./conda_env_files/pheniqs_env.yaml -p ~/conda_envs/pheniqs

      - name: install latex
        run: conda env create -f ./conda_env_files/latex_env.yaml -p ~/conda_envs/latex

        # - name: install nbconvert
        # run: conda env create -f ./conda_env_files/nbconvert_env.yaml -p ~/conda_envs/nbconvert;

      - name: Unit Tests
        run: python -m unittest ./mmeds/tests/unit/test_analysis.py
        # |
        #coverage run --parallel-mode --concurrency=multiprocessing ./mmeds/host/manager.py&
        # coverage run --parallel-mode --concurrency=multiprocessing ./mmeds/tests/unit/test.py;

      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: ../../../conda_env_files/jupyter_env.yaml
          activate-environment: jupyter
          auto-activate-base: false
      - name: jupyter run notebook
        if: always()
        run: jupyter nbconvert --to latex --template mod_revtex.tplx ~/mmeds_server_data/test_files/test_study/Qiime2_0/summary/mkstapylton@gmail.com-mattS-qiime2.ipynb --execute --ExecutePreprocessor.timeout=-1 --ExecutePreprocessor.kernel_name="jupyter"

      - name: check study output
        if: always()
        run: ls -ltR ~/mmeds_server_data/test_files/test_study

      - name: check jupyter output
        if: always()
        run: cat ~/mmeds_server_data/test_files/test_study/Qiime2_0/summary/mkstapylton@gmail.com-mattS-qiime2.ipynb

      - name: check notebook output
        if: always()
        run: cat ~/mmeds_server_data/test_files/test_study/Qiime2_0/summary/mkstapylton@gmail.com-mattS-qiime2.tex

      - name: Server Tests
        run: |
          pytest --cov=mmeds -W ignore::DeprecationWarning -W ignore::FutureWarning -s --durations=0 ./mmeds/tests/watcher/test_watcher.py&
          sleep 1;
          pytest --cov=mmeds -W ignore::DeprecationWarning -W ignore::FutureWarning -s ./mmeds/tests/server/test_server.py -x --durations=0;
      - name: Upload Server Coverage
        run: bash <(curl -s https://codecov.io/bash) -cF server;
      - name: Metadata Tests
        run: pytest --cov=mmeds -W ignore::DeprecationWarning -W ignore::FutureWarning -s ./mmeds/tests/metadata/test_error_metadata.py;
      - name: Upload Unit coverage
        run: bash <(curl -s https://codecov.io/bash) -cF unit;
