name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install packages
        run: sudo apt-get install tidy environment-modules xvfb -y
      - name: Start Services
        run: sudo systemctl start mysql.service; sudo systemctl start mongod.service;
