name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 5
    steps:
      - uses: actions/checkout@v2

      - name: cache Python modules
        uses: actions/cache@v2
        env:
          cache-name: python-cache
        with:
          path: $CONDA
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.pyc') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install packages
        run: sudo apt-get install tidy environment-modules xvfb -y
      - name: Start Services
        run: sudo systemctl start mysql.service; sudo systemctl start mongod.service;
      - name: Add conda to system path
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        run: echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: conda env update --file environment.yml --name mmeds-stable
      - name: Do MMEDs setup
        run: source activate mmeds-stable
      - name: Python install
        run: pip install .
      - name: Mysql Setup
        run: mysql -u root -proot < setup.sql | sed 's/\t/,/g' > out.csv
      - name: Server data setup
        run: mkdir ~/mmeds_server_data; cp -r ./test_files ~/mmeds_server_data/.
      - name: Unit Tests
        run: |
          coverage run --parallel-mode --concurrency=multiprocessing ./mmeds/host/manager.py&
          coverage run --parallel-mode --concurrency=multiprocessing ./mmeds/tests/unit/test.py
      - name: Upload Unit coverage
        run: bash <(curl -s https://codecov.io/bash) -cF unit;
      - name: Server Tests
        run: |
          coverage run --parallel-mode --concurrency=multiprocessing ./mmeds/host/manager.py&
          pytest --cov=mmeds -W ignore::DeprecationWarning -W ignore::FutureWarning -s ./mmeds/tests/server -x --durations=0
      - name: Upload Server Coverage
        run: bash <(curl -s https://codecov.io/bash) -cF server;
