name: MMEDs Tests

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 5
    steps:
      - name: Shutdown default
        run: sudo service mysql stop
      - uses: mirromutth/mysql-action@v1.1
        with:
          character set server: 'utf8'
          mysql root password: 'root'
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install packages
        run: sudo apt-get install tidy environment-modules -y
      - name: Start Services
        run: sudo systemctl start mysql.service; sudo systemctl start mongod.service;
      - name: Python install
        run: sudo python setup.py install
      - name: Check Verion
        run: mysql --version
      - name: Mysql Setup
        run: mysql -u root -proot < setup.sql
      - name: Server data setup
        run: mkdir ~/mmeds_server_data; cp -r ./test_files ~/mmeds_server_data/.
      - name: Unit Tests
        run: |
          coverage run --parallel-mode --concurrency=multiprocessing ./mmeds/host/manager.py&
          coverage run --parallel-mode --concurrency=multiprocessing ./mmeds/tests/unit/test.py;
      - name: Upload Unit coverage
        run: bash <(curl -s https://codecov.io/bash) -cF unit;
      - name: Server Tests
        run: |
          coverage run --parallel-mode --concurrency=multiprocessing ./mmeds/host/manager.py&
          pytest --cov=mmeds -W ignore::DeprecationWarning -W ignore::FutureWarning -s ./mmeds/tests/server -x --durations=0;
      - name: Upload Server Coverage
        run: bash <(curl -s https://codecov.io/bash) -cF server;
