name: MMEDs Tests

on: [push
]

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install packages
        run: sudo apt-get install tidy environment-modules -y; pip install cryptography;

      - name: install pandoc for nbconvert
        run: sudo apt-get install pandoc;

      - name: Start Services
        run: sudo systemctl start mysql.service; sudo systemctl start mongod.service;

      - name: Mysql Setup
        run: mysql -u root -proot < setup.sql

      - name: Server data setup
        run: mkdir /home/runner/mmeds_server_data; mkdir /home/runner/conda_envs; mkdir -p /home/runner/conda_env_files/pheniqs; mkdir -p /home/runner/.modules/modulefiles; cp -r ./test_files /home/runner/mmeds_server_data/.; cp ./mmeds/resources/mmeds_stats.yaml /home/runner/mmeds_server_data/.; cp -r ./modules/* /home/runner/.modules/modulefiles/.; cp -r ./conda_env_files/* /home/runner/conda_env_files/.;

      - name: Python install
        run: pip install wheel; pip install git+https://github.com/clemente-lab/mmeds-meta; sudo python setup.py install --verbose;

      - name: add bioconda channel for qiime
        run: conda config --append channels conda-forge --append channels bioconda --append channels defaults
      
        #- name: install qiime
        #run: conda env create -f ./conda_env_files/qiime2-2020.8_env.yaml -p /home/runner/conda_envs/qiime2-2020.8

        #- name: install jupyter
        #run: conda env create -f ./conda_env_files/jupyter_env.yaml -p /home/runner/conda_envs/jupyter

        #- name: install pheniqs
        #run: conda env create -f ./conda_env_files/pheniqs_env.yaml -p /home/runner/conda_envs/pheniqs

        #- name: install latex
        #run: conda env create -f ./conda_env_files/latex_env.yaml -p /home/runner/conda_envs/latex
      
      - name: Unit Tests
        run: |
         coverage run --parallel-mode --concurrency=multiprocessing ./mmeds/host/manager.py&
         coverage run --parallel-mode --concurrency=multiprocessing ./mmeds/tests/unit/test.py;

      - uses: actions/upload-artifact@v3
        with:
            name: summary-pdf-output
            path: /home/runner/mmeds_server_data/test_files/test_study/Qiime2_0/summary/mkstapylton@gmail.com-mattS-qiime2.pdf

      - name: Server Tests
        run: |
          pytest --cov=mmeds -W ignore::DeprecationWarning -W ignore::FutureWarning -s --durations=0 ./mmeds/tests/watcher/test_watcher.py&
          sleep 1;
          pytest --cov=mmeds -W ignore::DeprecationWarning -W ignore::FutureWarning -s ./mmeds/tests/server/test_server.py -x --durations=0;

      - name: Upload Server Coverage
        run: bash <(curl -s https://codecov.io/bash) -cF server;

      - name: Metadata Tests
        run: pytest --cov=mmeds -W ignore::DeprecationWarning -W ignore::FutureWarning -s ./mmeds/tests/metadata/test_error_metadata.py;

      - name: Upload Unit coverage
        run: bash <(curl -s https://codecov.io/bash) -cF unit;
